- Cargo.lock
- Cargo.toml
- compositor_common/Cargo.toml
- compositor_common/src/lib.rs
- compositor_common/src/scene.rs
For now I opted for every scene node to have a manually specified
resolution. I think we can add other ways of specifying resolution later
on.
The transformation hold their parameters as `Box<dyn Any>` for now. This will possibly change in the future, when we'll work on deserializing the scene from JSON.
> Add common crate

- .gitignore
- Cargo.lock
- Cargo.toml
- examples/common/common.rs
- examples/simple_ffmpeg.rs
- src/lib.rs
Add example that can be run with `cargo run --example simple_ffmpeg`
- send init request
- write output sdp and start listening on it with ffplay
- download sample mp4 file
- register input and output
- start streaming same via rtp to the input
> Add compositor example

- compositor_common/src/scene.rs
- compositor_render/src/lib.rs
- compositor_render/src/registry.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/texture.rs
- compositor_render/src/renderer/transformation.rs
This patch adds an initial implementation of the transformation registry. It also defines a `Transformation` trait. implementing it allows adding custom transformations.
Since we only accept manually defined resolutions, the API is quite simple.
Closes #8 .
> Add an initial implementation of the transformation registry

- compositor_common/src/frame.rs
- compositor_render/src/renderer.rs
This patch adds a `Renderer::render` and a `Renderer::update_scene` methods. Those are stubs for now (the `render` method just passes one of the source frames as the output)
> An initial `render` method.

- examples/common/common.rs
- examples/simple_ffmpeg.rs
- src/http.rs
- src/rtp_sender.rs
- src/state.rs
I went through https://github.com/mirror/x264/blob/eaa68fad9e5d201d42fde51665f2d137ae96baf0/encoder/encoder.c#L674 and for each field that is part of that check overridden ffmpeg defaults with libx264 defaults. I took the best-effort approach, the logic there is not straightforward, so I'm not 100% sure if I identified those defaults correctly.
Added preset as part of the API when creating and outputs. I'm also considering adding crf there(I'm open to suggestions).
> Adjust encoder settings and add config options to API

- examples/common/common.rs
- examples/long_ffmpeg.rs
- examples/simple_ffmpeg.rs
- src/rtp_sender.rs
Added a long-running example to see how the compositor behaves when running for longer periods.
I  noticed one issue for 4K streams encoder is keeping up only on the ultrafast preset. In all the other cases the number of messages in a channel grows steadily increasing memory usage.
I decided to start dropping the oldest frames when a number of messages in the queue is over 100 as a stop-gap solution, but when queue and renderer will be implemented this needs to be handled better.
1. Current approach (dropping frames in encoder): Easiest to implement and in most cases it gives the intended results, but it does not solve that issue for other places (e.g. what if renderer will not keep up). Also if new streams is pushing more data at the beginning we can stop dropping frames too early even …
> Add long running example

- .github/workflows/rust.yml
Trigger checks on PR to any branch or push to master. (push to branch without PR will not trigger CI now)
When some checks are in progress and new changes are pushed the old workflow will be cancelled (it does not apply to commits on master)
> [ci] Trigger checks only when needed

- src/rtp_receiver.rs
- src/rtp_sender.rs
Instead of using `10e9` I should have use `1e9` as a result pts passed to queue were 10x larger.
Initially I missed from_secs_f64 method on duration, using floats is easier in this case to define duration, so I decided to switch to it here.
> Fix pts calculation in rtp sender/receiver

- Cargo.lock
- compositor_render/Cargo.toml
- compositor_render/src/registry.rs
- compositor_render/src/render_loop.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/color_converter_pipeline.rs
- compositor_render/src/renderer/common_pipeline.rs
- compositor_render/src/renderer/rgba_to_yuv.wgsl
- compositor_render/src/renderer/scene.rs
- compositor_render/src/renderer/texture.rs
- compositor_render/src/renderer/yuv_to_rgba.wgsl
- compositor_render/src/transformations/web_renderer.rs
- examples/long_ffmpeg.rs
- examples/simple_ffmpeg.rs
This PR adds:
- conversion from YUV and RGBA
- conversion from RGBA to YUV
- some additional abstractions to wrap Textures
- fix simple_ffmpeg example
Code for interacting with wgpu is almost 1:1 from membrane plugin, only repackaged with some additional abstraction layers.
Tested on both examples:
- simple_ffmpeg (pass input into output)
- long_ffmpeg (use web renderer output)
Next steps:
- rework uploading and downloading between cpu<->gpu
- rescale frame on resolution change
- texture.rs is growing, so it's also time to brake it out into multiple modules
> Format conversion YUV <-> RGBA

- compositor_common/src/lib.rs
- compositor_render/src/lib.rs
- compositor_render/src/registry.rs
- compositor_render/src/renderer.rs
- examples/common/common.rs
- src/http.rs
- better error serialization (and pretty print in example)
- detect user errors and respond with 400 errors instead
- send proper Content-Type and Content-Lenght
> Improve errors returned from API

- compositor_common/src/validators/test.rs
- examples/text_renderer.rs
Current validation does not allow unused inputs, but we need at least one input to start pipeline (until https://github.com/membraneframework/video_compositor/issues/47 is addressed)
So to fix the example I added second output that is there just to pass input through
> Fix text text_renderer example

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/internal_queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- src/api.rs
- src/http.rs
- src/rtp_sender.rs
Add some basic queries e.g.
- get scene
- get registered inputs
- get registered output
(we could add bunch of other queries like that, I just picked those for start)
Add blocking query:
- WaitForNextFrame will block the response until the next frame will not show up in the queue
Break out some queue code into separate files.
~~Currently, I'm responding when a frame is enqueued. I think at this point we know that next render will include a frame (but not necessarily that one). I'm open 2 suggestions, I also considered:~~
- ~~calling callback when pushing frames to the renderer~~
- ~~have 2 different types of callback (one when enqueueing and one when pushing to renderer)~~
Response for input listener is sent when we send a frame from queue to renderer
Few small changes:
- drop unnecessary …
> Implement query API

- compositor_render/src/transformations/shader.rs
When implementing common transformations, I noticed that shader bind group layout docs were outdated. This updates it with the currently used layout.
> Fix shader bind group layout docs

- compositor_pipeline/src/pipeline.rs
- compositor_render/examples/silly.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/sync_renderer.rs
- compositor_render/src/transformations/shader.rs
This PR may be a bit weird, I cannot seem to find a place to put these scopes in that would feel good.
A quick explanation of how these error scopes work:
- you push an error scope to the device error scopes stack
- if an error happens it is caught by the scope
- you pop the error scope from the device stack and it returns one of the errors that it captured (if any)
- errors are captured only by the scope that is the highest on the stack and matches it's type (validation/oom)
> Add proper error handling for wgpu.

- Cargo.lock
- Cargo.toml
- compositor_common/Cargo.toml
- compositor_common/src/util.rs
- compositor_pipeline/Cargo.toml
- compositor_pipeline/src/pipeline.rs
- compositor_render/examples/silly.rs
- compositor_render/src/render_loop.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/renderer/texture.rs
- compositor_render/src/renderer/texture/utils.rs
- compositor_render/src/renderer/texture/yuv.rs
- compositor_render/src/sync_renderer.rs
- compositor_render/src/transformations/image_renderer.rs
- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/node.rs
- compositor_render/src/transformations/text_renderer.rs
- compositor_render/src/transformations/web_renderer.rs
- examples/long_ffmpeg.rs
- src/api.rs
- src/rtp_receiver.rs
- Instead of generating fake 2x2 texture make texture "Optional". The intention is that each component should decide how to handle missing frame e.g. shaders will convert mising frame to 1x1, but in the future we can e.g. change that behavior if there is only one input.
- If an empty frame is passed all the way to the output, we are filling it with black color
- If frame pts are older by more than the specified time (default 1 second) stop passing old frames to the pipeline. 
- Fix scene update: If scene update failed in old implementation it could break an old scene by removing all the input nodes. Now if scene update fails, old scene is not affected.
- InputTexture and NodeTexture now have  a method sate that returns Texture and BindingGroup.
- I wanted to avoid dealing with multiple …
> Pass missing frame through pipeline

- compositor_common/src/scene.rs
- compositor_common/src/validators.rs
- compositor_common/src/validators/test.rs
- compositor_render/examples/silly.rs
- compositor_render/src/render_loop.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/renderer/texture.rs
- compositor_render/src/transformations/shader/node.rs
- examples/long_ffmpeg.rs
Add fallback nodes:
- Fallback can be defined via fallback_id field in the nodes list in the scene_update request
- There is no way currently to define fallback for input explicitly, you need to have some pass-through transformation.
- There is no way to define fallback on output directly, you need to set it on the last node.
- Currently, we do not have any nodes that can result in missing texture, even if the input is missing, so for now I just added hack to the shader node that clears texture if input is empty and only one.
- Replaced node iterator in render_loop with a recursive walk through the scene, we can't use old approach because without knowledge whether render worked or not we do not know whether we need to render fallback nodes at all.
> Add fallback nodes

- compositor_chromium/src/client.rs
Process message handler in `cef::Client` allows receiving messages back from the renderer subprocess
> Add process message handler to `cef::Client`

- compositor_common/src/lib.rs
- compositor_common/src/renderer_spec.rs
- compositor_common/src/scene/builtin_transformations.rs
- compositor_common/src/validators.rs
- compositor_common/src/validators/test.rs
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline.rs
- compositor_render/examples/silly/silly.wgsl
- compositor_render/src/error.rs
- compositor_render/src/lib.rs
- compositor_render/src/registry.rs
- compositor_render/src/render_loop.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/node.rs
- compositor_render/src/renderer/renderers.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/sync_renderer.rs
- compositor_render/src/transformations/builtin/fixed_position_layout.wgsl
- compositor_render/src/transformations/builtin/transform_to_resolution/fill.wgsl
- compositor_render/src/transformations/builtin/transform_to_resolution/fit.wgsl
- compositor_render/src/transformations/builtin/transform_to_resolution/stretch.wgsl
- compositor_render/src/transformations/builtin/transformations.rs
- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/validation.rs
- compositor_render/src/transformations/shader_header.wgsl
- compositor_render/src/transformations/web_renderer.rs
- compositor_render/src/transformations/web_renderer/chromium.rs
- examples/common/common.rs
- src/api.rs
Changes (both introduced and proposed new patterns):
- Stop using names like RendererNewError, instead sth like InitRendererError or CrateRendererError, or if you really want to name it the same as method NewRendererError.
This is very subjective, but at least for me that word order is very confusing. If anyone disagrees I won't oppose it, but we need to decide specific naming convention. e.g. check here https://rust-lang.github.io/api-guidelines/naming.html#names-use-a-consistent-word-order-c-word-order
- This PR fixes issues introduced by a combination of PRs that added layout components and shader validation. (One PR introduced changes to shaders structure and the other still validated the old structure.
- This is not the final PR, but this already grew to much plus it's moving a lot …
> Improve error handling - part 2

- compositor_common/src/error.rs
- compositor_common/src/lib.rs
- compositor_common/src/scene.rs
- compositor_common/src/scene/builtin_transformations.rs
- compositor_common/src/scene/id.rs
- compositor_common/src/scene/node.rs
- compositor_common/src/scene/shader.rs
- compositor_common/src/scene/text_spec.rs
- compositor_common/src/scene/validation.rs
- compositor_common/src/scene/validation_test.rs
- compositor_common/src/util.rs
- compositor_render/examples/silly.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/error.rs
- compositor_render/src/transformations/shader/node.rs
- compositor_render/src/transformations/shader/validation.rs
Initially, this PR was aiming to address https://github.com/membraneframework/video_compositor/issues/108, but while implementing it I realized that it would complicate the implementation without any significant upside. It's very unlikely that we ever forgot to validate the scene when this is only done in place and it's one of the most important endpoints in our API.
Changes here are mostly moving stuff around, improving error messages and small refractors here and there. I'll add more in comments.
> Refactor scene validation code

- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/error.rs
- compositor_render/src/transformations/shader/validation.rs
Improve errors especially focusing on type comparisons. Serialization for values is not intended to cover everything in some cases I just left some simplified representation or default debug format. I'm open to suggestions on what to do with cases that we are not serializing exactly, but I don't think we should handle all the cases.
Example error:
before:
```
Type internal structure doesn't match:
Expected:
BindingArray {
base: [9],
size: Constant(
[1],
),
}
Actual:
Sampler {
comparison: false,
}.
```
after
```
Type mismatch (expected: binding_array<texture_2d<f32>, 16>, actual: sampler)
```
> Improve shader errors

- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline.rs
- compositor_render/src/error.rs
- compositor_render/src/lib.rs
- compositor_render/src/registry.rs
- compositor_render/src/sync_renderer.rs
- compositor_render/src/validation.rs
- src/api.rs
> Implement unregistering renderers

- compositor_render/src/transformations/web_renderer.rs
- compositor_render/src/transformations/web_renderer/browser.rs
When input finishes, fallback is triggered and the web render method is not called. It causes `painted_frames_receiver ` to grow because the frames are not being actively read.
I fixed it by limiting the amount of frames the channel is able to receive.
Fixes #141
> Fix memory leak in web renderer

- compositor_common/src/scene/builtin_transformations.rs
I used functions instead of impl default for `HorizontalAlign` and `VerticalAlign`, because in other cases `Center` might not be a good default value (e.g. text alignment)
> Add defaults fit alignments

- compositor_common/src/scene/node.rs
- compositor_common/src/scene/text_spec.rs
- compositor_render/src/renderer/node.rs
- compositor_render/src/transformations/text_renderer.rs
- examples/image.rs
- examples/text.rs
While writing docs I noticed few issues with text renderer API
- rename example name
- change node type `text_renderer` -> `text`
- rename `resolution` -> `dimensions`
- Avoid 2 nested resolution fields in fixed type
> Change text renderer api

- compositor_render/examples/silly/silly.wgsl
- compositor_render/src/gpu_shader/error.rs
- compositor_render/src/gpu_shader/pipeline.rs
- compositor_render/src/gpu_shader/shader_header.wgsl
- compositor_render/src/gpu_shader/validation.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/common_pipeline.rs
- compositor_render/src/renderer/common_pipeline/surface.rs
- compositor_render/src/renderer/node.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/transformations/builtin/apply_transformation_matrix.wgsl
- compositor_render/src/transformations/builtin/corners_rounding.wgsl
- compositor_render/src/transformations/builtin/mirror_image.wgsl
- Follow up to PR when we switched back to stack trace approach (remove some concatenated errors)
- Improve wording, fix some typos
- Improve serialization for errors (mostly focused on comparing types from shader with ShaderParam)
- Replace unwraps in validation code with safer alternative
`.unwrap_with("<unnamed>")` is just to make it shorter. Without this I would have to write
`.clone().unwrap_or_else(|| "<unnamed>".to_string())` everywhere.
> Improve shader validation errors

- .github/workflows/package_for_release.yml
- .github/workflows/shellcheck.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- RELEASE.md
- compositor_chromium/Cargo.toml
- compositor_chromium/chromium_sys/build.rs
- compositor_chromium/examples/simple.rs
- compositor_chromium/src/settings.rs
- compositor_chromium/src/utils.rs
- examples/web_renderer.rs
- scripts/compositor_runtime_wrapper.sh
- scripts/release.sh
- src/bin/main_process.rs
- src/bin/package_for_release/bundle_linux.rs
- src/bin/package_for_release/bundle_macos.rs
- src/bin/package_for_release/main.rs
- src/bin/package_for_release/utils.rs
Release process for Linux binaries + docs
> Release pipeline

- compositor_pipeline/src/pipeline.rs
starting the pipeline twice gives a very cryptic error becaus muxer receives non monotonic dts from encoder
> Check if pipeline already started

- Dockerfile
- examples/docker.rs
You can enable the support by setting the environment variable `NVIDIA=1`
> Add support for nvidia GPUs in the docker example

- compositor_common/src/scene/node.rs
specs defined inside transition were not validated
> Validate builtin spec inside transition

- README.md
If RTC.ON workshops repo becomes outdated due to API change, then I would suggest adding a note about it. Currently, I find adding a note about such a possibility unnecessary and potentially confusing.
> Add RTC.ON workshops link to readme

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- src/rtp_receiver.rs
The RTP receiver is only responsible for receiving the packets now.
> Extract the decoder into the internal part of the library.

- Cargo.lock
- compositor_pipeline/src/error.rs
- compositor_render/Cargo.toml
- compositor_render/src/error.rs
- compositor_render/src/renderer/node.rs
- compositor_render/src/renderer/renderers.rs
- compositor_render/src/transformations.rs
- compositor_render/src/transformations/layout.rs
- compositor_render/src/transformations/layout/apply_layouts.wgsl
- compositor_render/src/transformations/layout/layout_renderer.rs
- compositor_render/src/transformations/layout/params.rs
- compositor_render/src/transformations/layout/shader.rs
- compositor_render/src/transformations/layout/transformation_matrix.rs
- compositor_render/src/wgpu/shader.rs
- compositor_render/src/wgpu/shader/pipeline.rs
- compositor_render/src/wgpu/texture/base.rs
- Copy WgpuShader and Pipeline implementation + extract some common parts to avoid duplication
- Create a new Layout node (it's not constructible via API)
I tested that by hardcoding layout inside some fake implentation
> Add generic layout component

- .github/workflows/rust.yml
- .gitignore
- compositor_render/src/scene/scene_state.rs
- snapshot_tests/simple_input_pass_through.scene.json
- snapshot_tests/view/constant_width_and_height_views_row.scene.json
- snapshot_tests/view/constant_width_views_row.scene.json
- snapshot_tests/view/constant_width_views_row_with_overflow.scene.json
- snapshot_tests/view/dynamic_and_constant_width_views_row.scene.json
- snapshot_tests/view/dynamic_and_constant_width_views_row_with_overflow.scene.json
- snapshot_tests/view/dynamic_width_views_row.scene.json
- src/api.rs
- src/bin/update_snapshots/main.rs
- src/main.rs
- src/snapshot_tests.rs
- src/snapshot_tests/test_case.rs
- src/snapshot_tests/tests.rs
- src/snapshot_tests/utils.rs
- src/types/convert.rs
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/4
This PR includes:
- cherry picked https://github.com/membraneframework/video_compositor/commit/bf448457c6d75e91b1abceb9b2c2d5643730946c
- https://github.com/membraneframework/video_compositor/pull/249/commits/96ef574c36659744065bb43bf05e558c45ff1392
- update test code to use new types
- simplify + refactor parts of the test implementation
- Add tests for `View` and remove the old test
Given that this PR includes commit cherry picked from master I will merge this PR without squashing
> Fix tests for new API + add `View` tests

- compositor_render/src/scene.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/scene/view_component.rs
- compositor_render/src/transformations/layout.rs
- schemas/scene.schema.json
- snapshot_tests/view/root_view_with_background_color.scene.json
- snapshot_tests/view/view_with_relative_positioning_partially_covered_by_sibling.scene.json
- snapshot_tests/view/view_with_relative_positioning_render_over_siblings.scene.json
- src/snapshot_tests/tests.rs
- src/types/component.rs
- src/types/from_component.rs
- https://github.com/membraneframework/video_compositor/pull/250/commits/1917333ffb0d09e7dd8b1c9b7f3b21a1a0b9ac84 Add relative positioning to view (it's intended to be supported in other layout components)
- https://github.com/membraneframework/video_compositor/pull/250/commits/929739d11363d7a6eaae2714088f7a651dd14060 Fix counting child nodes (old implementation wouldn't work for components where not all children are part of a layout tree)
- Fix rendering background on component that is a root of a node
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/5
> Add relative positioning support for layout components

- .gitignore
- src/bin/generate_wiki/docs_builder.rs
- src/bin/generate_wiki/main.rs
- src/bin/generate_wiki/types.rs
In this PR I implemented basic docs generation from rust types. There are still some imperfections and the code itself needs a refactor. I will fix it in the follow-up PR.
Example documentation page:
```typescript
type View = {
background_color_rgba?: string,
bottom?: f32,
children?: Component[],
direction?: "row" | "column",
height?: f32,
id?: string,
left?: f32,
overflow?: "visible" | "hidden" | "fit",
right?: f32,
rotation?: f32,
top?: f32,
transition?: Transition,
type: "view",
width?: f32,
}
```
- `background_color_rgba` - Background color of a component in a "#RRGGBBAA" format. Defaults to transparent "#00000000".
- `bottom` - Distance between the bottom edge of this component and the bottom edge of its parent. If this field is defined, this element will be absolutely positioned, …
> Generate wiki from rust types

- .gitignore
- Cargo.lock
- src/bin/generate_docs/main.rs
- src/bin/generate_docs/parsing.rs
- src/bin/generate_docs/type_definition.rs
Components currently are generated in the `/components` directory because the website expects the components to be there. Once the new website PR gets merged I will change it to `/generated`
> [docs] Add docs generation for renderers

- docs/pages/api/components/Image.md
- docs/pages/api/components/InputStream.md
- docs/pages/api/components/Rescaler.md
- docs/pages/api/components/Shader.md
- docs/pages/api/components/Text.md
- docs/pages/api/components/Tiles.md
- docs/pages/api/components/View.md
- docs/pages/api/components/WebView.md
- docs/pages/api/io.md
- docs/pages/api/renderers/image.md
- docs/pages/api/renderers/shader.md
- docs/pages/api/renderers/web.md
- docs/pages/api/routes.md
- docs/pages/common/absolute-position.md
- docs/sidebars.ts
- schemas/register.schema.json
- schemas/scene.schema.json
- src/bin/generate_docs/main.rs
- src/bin/generate_docs/type_definition.rs
- src/types/component.rs
- src/types/renderer.rs
- hide table of contents for generated pages
- change coma to semicolon in the type definitions
- update main routes page (it had old info + links pointing to wiki)
- replace Image renderer definition with custom text
- replace Shader component definition with custom text
- extract common text fragment explaining absolute positioning
- change `(default=sth` to `(**default=sth**)`. I tried to move `**` outside of `()` but one of star is cut of when genering schema.
> [docs] Replace generated docs + some style changes + update

- compositor_render/src/transformations/layout.rs
- compositor_render/src/transformations/layout/flatten.rs
- package-lock.json
- snapshot_tests/view/overflow_hidden_with_input_stream_children.scene.json
- snapshot_tests/view/overflow_hidden_with_view_children.scene.json
- src/snapshot_tests/tests.rs
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/22
Detect a few common cases where we don't need to pass a layout to the shader
> Optimize amount of renders

- README.md
API has changed significantly and the workshop repo is no longer a good place to look up examples
> Remove RTC.ON workshops url

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- src/rtp_receiver.rs
Fixes an issue with lost frames when the UDP buffer is small.
The main fix is to change the channel of size 1 to an unbound channel. Decoding was a bottleneck for reading. Not sure if adding `Arc` helps much.
> Improve latency when reading from UDP buffer

- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/shader/validation/error.rs
- compositor_render/src/wgpu/common_pipeline.rs
- src/types/from_renderer.rs
Before:
```console
Error stack:
- Failed to register shader "shader_example_1".
- Shader parse error: expected ';', found 'return'
```
After:
```console
Error stack:
- Failed to register shader "shader_example_1".
- Shader parsing error in line 18 column 5.
- expected ';', found 'return'
```
The last line is not formatted according to the convention, due to using `naga::front::wgsl::ParseError` as a source (the error message comes directly from naga). I don't want to manually change it, because this might make errors less readable (e.g. first word is case sensitive variable name, the dot at the end interferes with the provided syntax error making it misleading, etc.)
> Add location in parse shader error message

- Cargo.lock
- Cargo.toml
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- examples/simple.rs
- src/rtp_receiver.rs
- src/rtp_sender.rs
This patch removes the `smol` async runtime. As it turns out, it is weirdly slow when sending stuff through channels.
It also makes the receive buffer larger in the UDP socket (if the OS allows it) and moves RTP depacketizing to the decoder thread.
Additionally, it removes `Arc`s from this code, since RTP packets are cheap to copy already (the header is very small and the contents use `Bytes`, which have smart copying already).
> Improve the handling of UDP inputs.

- Cargo.lock
- Cargo.toml
- compositor_render/Cargo.toml
- examples/docker.rs
- examples/image.rs
- examples/simple.rs
- examples/test_pattern.rs
- examples/text.rs
- examples/tiles.rs
- examples/transition.rs
- examples/web_view.rs
- src/bin/main_process.rs
- src/bin/package_for_release/bundle_linux.rs
- src/bin/package_for_release/bundle_macos.rs
- src/bin/process_helper/main.rs
- src/lib.rs
- src/logger.rs
- src/main.rs
- Use tracing library
- Default to json logger when not building from source (based on CARGO_MANIFEST_DIR env)
- Add env `FFMPEG_LOG_LEVEL` that controll ffmpeg logs (default to warn)
> Switch from `env_logger` to `tracing`

- Dockerfile
- compositor_render/src/transformations/web_renderer/chromium_context.rs
- docker/entrypoint.sh
The main problem was that the `/dev/shm` partition was too small inside the container. `disable-dev-shm-usage` flag works around the issue by using a temporary directory instead.
Closes #307
> Fixed running web renderer in docker container

- Cargo.lock
- Cargo.toml
- compositor_pipeline/src/pipeline.rs
- compositor_render/src/transformations/web_renderer.rs
- compositor_render/src/transformations/web_renderer/chromium_context.rs
- docs/pages/api/api.md
- docs/pages/api/routes.md
- docs/pages/deployment/configuration.md
- docs/sidebars.ts
- examples/common/common.rs
- examples/docker.rs
- examples/image.rs
- examples/simple.rs
- examples/test_pattern.rs
- examples/text.rs
- examples/tiles.rs
- examples/transition.rs
- examples/web_view.rs
- src/api.rs
- src/bin/main_process.rs
- src/config.rs
- src/http.rs
- src/lib.rs
- src/logger.rs
- src/main.rs
- src/snapshot_tests/utils.rs
- src/types.rs
- src/types/convert.rs
Switch to env base config
Why not init request:
- some values need to be set before e.g. API PORT, so it requires using both methods of configuration
- it's very non-standard config method, even if it was the best option it could be perceived as hack.
Why not config files:
- hard to work with in prod environment, to add config inside k8s or any other container-based platform you would need to: create some volume entity from that file, attach/mount that volume to the container, and pass some env that defines the path where compositor should look for the file. 
- hard to work with in a dev environment. To tests some other configuration you need to modify a file. If we want to persist the config we can always use `.env` file.
> Switch to env based configuration + remove `"init"` request

- examples/image.rs
- examples/simple.rs
- examples/test_pattern.rs
- examples/text.rs
- examples/tiles.rs
- examples/transition.rs
In every example we either need to set LIVE_COMPOSITOR_WEB_RENDERER_ENABLE to 0 or run `compositor_chromium::cef::bundle_for_development`
I decided to disable it everywhere except `web_view` example. Note that those examples are still building compositor with `web_renderer` feature enabled it's just not initialized in runtime.
> Disable web renderer in non-web examples

- Cargo.lock
- Cargo.toml
- compositor_pipeline/Cargo.toml
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/lib.rs
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- compositor_pipeline/src/pipeline/decoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/input.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/structs.rs
- src/api.rs
- src/api/register_request.rs
- src/lib.rs
- src/main.rs
- src/rtp_sender.rs
This patch makes it simple to add more inputs and more decoders. It also removes the generics from the pipeline in favor of simple enums. The implementation of the RTP receiver was also moved to the `compositor_pipeline` crate.
A big fault of this patch is that it doesn't address attaching multiple decoders to a single input, but this requires further discussion.
> Refactor the input architecture.

- build-tools/docker/full.Dockerfile
```
Unable to set up transient service directory: XDG_RUNTIME_DIR "/tmp" is owned by uid 0, not our uid 1001
```
> Fix `XDG_RUNTIME_DIR` env error in Docker

- compositor_render/src/scene.rs
- compositor_render/src/scene/components/interpolation.rs
- compositor_render/src/scene/rescaler_component.rs
- compositor_render/src/scene/rescaler_component/interpolation.rs
- compositor_render/src/scene/tiles_component.rs
- compositor_render/src/scene/tiles_component/interpolation.rs
- compositor_render/src/scene/transition.rs
- compositor_render/src/scene/types.rs
- compositor_render/src/scene/view_component.rs
- compositor_render/src/scene/view_component/interpolation.rs
- Remove duplicated code around transitions (and recover old transitions)
- Add type that represents interpolation type
- Fix calculation when recovering the transition state from the previous state. Old implementation worked only for linear transitions.
I started implementing transition based on cubic bezier curve, but it appears to be more complicated than I expected so I left it for now with just linear.
> Fix interpolation abstraction for non linear transitions

- docs/pages/api/routes.md
Docs for RegisterInputRequest were not supposed to be generated. There are a few problems with that change:
- headers are the wrong size, when other types use `###` the `RegisterInputRequest` is using `##`
- imported markdown files do not show up in markdown
For now, I manually copied generated docs and changed headers to look consistent. This is just a temporary fix, it needs to be addressed better.
> [docs] Fix inconsistent header sizing in routes page

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_render/src/state.rs
- compositor_render/src/wgpu/ctx.rs
- docs/pages/api/routes.md
- docs/pages/deployment/configuration.md
- src/api.rs
- src/config.rs
- src/snapshot_tests/utils.rs
- Add `LIVE_COMPOSITOR_FORCE_GPU` env
- Improve logging defaults to avoid log spam
- Display useful info about available adpaters
It looks like M1 metal is detected as CPU, but given that this option is mostly useful for deployment purposes then I think it's still fine
> Add option to force GPU rendering

- .github/workflows/package_for_release.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
> Switch to macos-14 image for release build

- compositor_render/src/lib.rs
- compositor_render/src/state.rs
- compositor_render/src/wgpu.rs
- compositor_render/src/wgpu/ctx.rs
- src/bin/update_snapshots/main.rs
- src/snapshot_tests.rs
This allows us to create many hundreds of renderers in snapshot tests. It used to fail on NVIDIA drivers, and it works now.
closes #332
> Add an option to create the `WgpuCtx` once and reuse it.

- .github/workflows/check.yml
- compositor_pipeline/src/pipeline.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/scene/validation.rs
- compositor_render/src/state.rs
- compositor_render/src/state/node.rs
- compositor_render/src/state/render_graph.rs
- compositor_render/src/state/render_loop.rs
- compositor_render/src/transformations/layout.rs
- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/node.rs
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/web_renderer.rs
- compositor_render/src/transformations/web_renderer/chromium_sender.rs
- compositor_render/src/transformations/web_renderer/disabled_renderer.rs
- compositor_render/src/transformations/web_renderer/embedder.rs
- compositor_render/src/transformations/web_renderer/node.rs
- compositor_render/src/transformations/web_renderer/renderer.rs
- compositor_render/src/types.rs
- compositor_render/src/wgpu/texture.rs
- examples/pass_through.rs
- src/snapshot_tests/utils.rs
- src/types/from_renderer.rs
- ensure variant without chrome builds on CI
- pass information about register/unregistering inputs and unregistering output is passed to renderer (register output is not necessary now, but it will be added in follow up)
- removed fallback code. Until now fallback code was left there because we want to address that issue, but don't know how yet, plus it didn't cost us any maintenance overhead, but now it makes it harder so I removed it.
- internals
- nodes do not have an ids right now (they were only needed to establish edges of the graph)
- render graph is now a tree
> Support per-output scene updates in renderer

- .github/workflows/check.yml
Sth must have changed on GitHub actions and there is not enough space for our current check job.
tests itself seem to be the most problematic, so I run git clean before them and there is no rust steps after that.
> [ci] Fix `"no space left on the device"` error

- Cargo.lock
- compositor_render/Cargo.toml
- compositor_render/src/transformations/layout/shader.rs
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/shader/validation.rs
- compositor_render/src/transformations/shader/validation/error.rs
- compositor_render/src/transformations/text_renderer.rs
- compositor_render/src/transformations/web_renderer/shader.rs
- compositor_render/src/wgpu/ctx.rs
- compositor_render/src/wgpu/format/rgba_to_yuv.rs
- compositor_render/src/wgpu/format/yuv_to_rgba.rs
- compositor_render/src/wgpu/texture/base.rs
- compositor_render/src/wgpu/utils/r8_fill_with_color.rs
Text layouting was very slightly changed in the new `glyphon` version, and one snapshot needs to be updated: membraneframework-labs/video_compositor_snapshot_tests#26
There are some breaking changes in `wgpu`, which force us to change our code:
- in `wgpu::RenderPassColorAttachment`:
- the `store` field in `wgpu::Operations` is now an enum instead of a bool
- two new fields were added, `timestamp_writes` and `occlusion_query_set`. Both are used for debugging and performance measurements
- in `naga`, the shader parser:
- `ArraySize` was simplified a lot. `ArraySize::Constant` no longer holds a generic shader constant (which could be negative for example). It's represented as a `NonZeroU32` now, which allows us to simplify the array size evaluation code. Because of this change we also don't …
> Update wgpu to 0.19.1

- Cargo.lock
- Cargo.toml
- compositor_pipeline/Cargo.toml
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- compositor_pipeline/src/pipeline/decoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/decoder/opus_decoder.rs
- compositor_pipeline/src/pipeline/input/mp4.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/audio_queue_thread.rs
- compositor_pipeline/src/queue/utils.rs
- compositor_pipeline/src/queue/video_queue.rs
- compositor_pipeline/src/queue/video_queue_thread.rs
- compositor_render/src/types.rs
- src/api.rs
- src/types/from_register_request.rs
- Refactor queues to store just one HashMap
- use chrono::Duration for offset calculations (supports negative values)
- remove code from mp4 code that simulates real-time
- add queue between decoder and queue
- decoder <-> queue - bounded channel 10
- mp4 <-> decoder - bounded channel 10
- rtp - for now  unbounded
- ~~[REGRESSION] I removed sleep which ensured buffer was filled. (I'm working on that, but I'm not sure if this will be part of this PR or a follow up)~~
- resolved in https://github.com/membraneframework/video_compositor/pull/383/commits/9c85719dc90b778e256d782b85729ff3144ade27
For now, I just did minimal testing + ~~I'm still looking into replacement for sleep~~, but I think this PR is complete enough for review.
> Implement control flow for elements before queue

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/pipeline/pipeline_output.rs
- compositor_pipeline/src/queue/audio_queue_thread.rs
- compositor_pipeline/src/queue/video_queue_thread.rs
- src/api/register_request.rs
- src/types/from_register_request.rs
- src/types/register_request.rs
The main change here is changing `send` in queue to `try_send`/`send_deadline`. Other changes in this PR are only partially related to control flow:
- remove code that drops output frames from the pipeline and encoder
- change all unbound queues to bound(5)
- refactor output registration code (just moving stuff around, no changes in behavior)
- for audio there is large buffer, so just try_send is fine
- for video, we have very small buffers, so `send_deadline` needs to be used to check against buffer size how long we can wait.
> Implement control flow for elements after queue

- compositor_render/src/scene.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/scene/web_view_component.rs
- compositor_render/src/state/node.rs
- compositor_render/src/transformations/web_renderer/chromium_sender.rs
- compositor_render/src/transformations/web_renderer/chromium_sender_thread.rs
- compositor_render/src/transformations/web_renderer/disabled_renderer.rs
- compositor_render/src/transformations/web_renderer/embedder.rs
- compositor_render/src/transformations/web_renderer/node.rs
- compositor_render/src/transformations/web_renderer/renderer.rs
- examples/web_view.html
- examples/web_view.rs
- src/bin/process_helper/handler.rs
- src/bin/process_helper/render_frame.js
- src/bin/process_helper/state.rs
Currently, users have to specify HTML elements that display frames in the `register_inputs` JS function.
For example:
```html
<body>
<canvas id="my_video"></canvas>
</body>
<script>
register_inputs("my_video")
</script>
```
The problems with this approach:
- Code editors don't know about `register_inputs` so they show an error
- You can't test the website in a normal browser because the browser would also show an error 
- The embedding config isn't in one place
- It could cause problems for react or similar libraries
The new approach uses component IDs for specifying IDs of HTML elements.
```ts
{
"output_id": "output_1",
"root": {
"id": "embed_input_on_website",
"type": "web_view",
"instance_id": "example_website",
"children": [
{
"id": "my_video", // <-- here
"type": "input_stream", …
```
> Remove `register_inputs` from web renderer

- Cargo.lock
- compositor_pipeline/Cargo.toml
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- compositor_pipeline/src/pipeline/decoder/fdk_aac.rs
- compositor_pipeline/src/pipeline/input.rs
- compositor_pipeline/src/pipeline/input/mp4.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/input/rtp/depayloader.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/pipeline/structs.rs
- src/types/from_register_request.rs
This PR uses the FDK deocder for decoding and Symphonia for demuxing. Most MP4s should work in this configuration. The remaining work is:
- allow OPUS decoding for MP4s
- allow AAC decoding for RTP
Closes #374
> Add AAC decoding for MP4 files.

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/input/rtp/tcp_server.rs
- compositor_pipeline/src/pipeline/input/rtp/udp.rs
- examples/rtp_tcp.rs
- schemas/register.schema.json
- src/types/from_register_request.rs
- src/types/register_request.rs
Add `transport_protocol` field to request that registers rtp input stream.  Option for tcp is called `tcp_server` to indicate the direction, but I don't plan to ever implement `tcp_client` variant.
> Implement RTP over TCP on input

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
When we schedule unregistered requests, they happen on the queue thread, so they are blocking the queue.
This PR modify unregister logic to avoid blocking.
- Make channels on output as small as possible
- Now when output unregister happens
- frames in channel between queue and renderer will be lost
- frames in encoder and RTP UDP sender will still be delivered
- frames in RTP TCP sender will be delivered unless:
- TCP socket is not connected
- TCP connection exists but writing takes longer than 30 seconds
> Non-blocking unregistered requests.

- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/encoder/opus_encoder.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/input/rtp/depayloader.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_pipeline/src/pipeline/output/rtp/payloader.rs
- compositor_pipeline/src/pipeline/pipeline_output.rs
- compositor_pipeline/src/pipeline/rtp.rs
- examples/audio.rs
- examples/common/common.rs
- examples/docker.rs
- examples/image.rs
- examples/mp4.rs
- examples/pass_through.rs
- examples/simple.rs
- examples/test_pattern.rs
- examples/text.rs
- examples/tiles.rs
- examples/transition.rs
- examples/web_view.rs
- schemas/register.schema.json
- src/types/from_register_request.rs
- src/types/register_request.rs
Implements audio encoding and sending to output via RTP.
Audio in the example is 0.5-2s behind video since in the example I use 2 FFmpeg processes spawned separately. I couldn't send both video and audio on a single port via FFmpeg.
TODO:
Add resampling and mixing
> Audio output - encoding and RTP sending

- compositor_pipeline/src/queue/queue_thread.rs
- src/config.rs
When debuging slow membrane pipeline it was hard to identify the bottelnecek because we were not sure if compositor receives data or not.
- Add log when we are pusing samples/frames to renderer or mixer before all inputs are ready
- Lower fallback timeout from 2000ms to 500ms. (Unrelated to this issue, I just think this value is to large, it should significantlly larger than any reasonable distance between frames, but small enough so user does not notice the freeze)
> Log missing frames + lower stream fallback to 500 ms

- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- docs/pages/deployment/configuration.md
- src/config.rs
The current default behavior was a bug in my opinion, events that are scheduled in the past should be discarded. Additionally, this PR leaves previous behavior under the configuration env.
I'm open to suggestions for better env name
> Add `LIVE_COMPOSITOR_RUN_LATE_SCHEDULED_EVENTS` config option

- compositor_pipeline/src/pipeline/output/rtp/packet_stream.rs
- compositor_pipeline/src/pipeline/output/rtp/payloader.rs
Most likely fixes https://swmansion.slack.com/archives/C06GLUH09FE/p1710407272484879
```
{"timestamp":"2024-03-14T09:01:58.629417Z","level":"ERROR","fields":{"message":"Failed to payload a packet: Tried to payload audio with non audio payloader."},"target":"compositor_pipeline::pipeline::output::rtp::tcp_server","span":{"output_id":"video_output_1","name":"RTP sender"},"spans":[{"output_id":"video_output_1","name":"RTP sender"}]}
{"timestamp":"2024-03-14T09:01:58.629419Z","level":"ERROR","fields":{"message":"Failed to payload a packet: Tried to payload audio with non audio payloader."},"target":"compositor_pipeline::pipeline::output::rtp::tcp_server","span":{"output_id":"video_output_1","name":"RTP sender"},"spans":[{"output_id":"video_output_1","name":"RTP sender"}]} …
```
> Fix EOS for rtp output payloader

- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- compositor_pipeline/src/queue/utils.rs
- compositor_pipeline/src/queue/video_queue.rs
If queue is behind real-time (or far into the future) offset of incoming streams (if not provided explicitly) is calculated based on the real time. As a result:
- If queue is behind real-time then the initial frame will be calculated based on real-time, so the PTS of the frame will be larger than PTS of what queue that is already processing. This will result in the first frame frozen at the beginning
- If a queue is faster than real-time then the initial frame will be calculated in the past which will cause the initial stream to be dropped.
Technically the above behavior is not wrong, but it's also not useful.
This can happen if you have required and not required inputs, where some of the inputs do not have the offset defined. Of course, if you do not process in real-time then sending …
> Handle initial offset for mixed offline/online streams

- build_tools/nix/flake.nix
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- src/api/register_request.rs
Closes #432 
If creating decoder or initializing input takes some time it will no longer block main processing pipeline
> Allow heavy operations in input registration

- build_tools/nix/flake.nix
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/pipeline/pipeline_output.rs
- src/api/register_request.rs
Currently, if the initial scene is not correct, the output registration will throw an error but output will still be registered.
> Abort registration if initial scene is not correct

- docs/pages/api/routes.md
- docs/pages/deployment/configuration.md
- src/api.rs
- src/config.rs
- src/routes.rs
This value will be used in the plugin to verify that we are connecting to the correct instance. With the current plugin implementation, it's possible to connect by mistake to the existing compositor instance.
> Add instane_id to the compositore and return it in `GET /status`

- compositor_integration_tests/src/tests/simple.rs
- compositor_integration_tests/src/validation.rs
I couldn't reproduce the problem locally but I believe it's caused by wrongly chosen timestamps.
The test video consists of images where each image appears for 1 second. I used timestamps that were at the transition between images
> Fix integration tests sometimes failing

- docs/pages/deployment/configuration.md
- src/config.rs
I noticed that configuration docs were inconsistent
Added missing defaults, fixed the wrong ones, recorded config code to match docs (it's easier to check it once it follows the same order)
> Make configuration docs consistent

- compositor_pipeline/src/pipeline/decoder/video/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/input/rtp/depayloader.rs
This also turns off the ffmpeg decoder option that allowed delivering non-au-aligned data.
> Split RTP-depayloaded packets using the marker bit.

- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- docs/pages/deployment/configuration.md
- src/config.rs
With the current setup if you have:
- ahead of time processing enabled
- there is no inputs
- and machine is not able to encode/render frames in real time
then queue will drop some output frames
> Support offline processing without any inputs

- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- docs/pages/api/outputs/rtp.md
- schemas/register.schema.json
- src/types/from_register_request.rs
- src/types/register_request.rs
I'm not sure about the field name, other options I considered:
- `extra_options`
- `ffmpeg_extra_options`
- `raw_ffmpeg_options`
- `ffmpeg_overrides`
> Add option to provide raw FFmpeg options

- compositor_integration_tests/src/compositor_instance.rs
- compositor_integration_tests/src/tests/audio_mixing.rs
- compositor_integration_tests/src/tests/muxed_video_audio.rs
- compositor_integration_tests/src/tests/required_inputs.rs
- compositor_integration_tests/src/tests/schedule_update.rs
- compositor_integration_tests/src/tests/unregistering.rs
- Dynamically find ports to use without a collision (start from 10000 port and increment)
- Replace sleep after instance creation with periodic check if http serer is up
> Dynamically assign ports in tests

- build_tools/nix/flake.lock
- build_tools/nix/flake.nix
It does not look like nix packages were affected, but we are downgrading just to be safe.
> Downgrade nixpkgs to older xz

- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- compositor_pipeline/src/queue/video_queue.rs
- integration_tests/src/compositor_instance.rs
- integration_tests/src/tests.rs
- integration_tests/src/tests/push_input_before_start.rs
The current implementation for dropping frames before starting did not work correctly.
- Frames/samples were not dropped
- When the compositor started initial frames were treated as zero, which resulted in sending a few initial frames that should have been dropped to the renderer.
- Tested on video
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/32
> Fix sending input stream before start

- compositor_pipeline/src/pipeline/decoder/audio.rs
- compositor_pipeline/src/pipeline/decoder/audio/resampler.rs
- compositor_pipeline/src/pipeline/input/mp4/mp4_file_reader.rs
- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/utils.rs
When starting the compositor sample batch can start before the queue starts and after that. Because the PTS of samples can't be negative number the batch range of (-10ms, 10ms) would be converted to `(0, 10ms)` but still contain 20ms worth of samples. As a result, the mixer is detecting overlapping samples and printing warnings.
Additionally, add some logs + fix incorrect spans
> Do not mix sample batches older than queue start

- compositor_render/src/scene.rs
- compositor_render/src/transformations/image_renderer.rs
I'll add `todo!()` CI check in the next PR
> Implement missing branches - remove leftover panicing `todo!()`-s

- src/server.rs
If you use `_` in rust then the value will be dropped immediately, so in this case server is crashing on startup because channel was closed
> Fix server startup

- src/bin/generate_docs/docs_config.rs
Port type was renamed to PortOrPortRange
> [docs] Fix inlining `PortOrPortRange` type

- compositor_render/src/scene.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/scene/types.rs
- snapshot_tests/tiles/video_call_with_labels.scene.json
- src/bin/update_snapshots/main.rs
- src/snapshot_tests/tests.rs
- src/types/from_component.rs
When creating absolutely positioned element inherit the width/height of a parent if it's not provided.
I'll update docs in a follow up.
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/35
> Inherit width/height in absolute positioning

- compositor_pipeline/src/pipeline.rs
When output receives eos based on `should_send_eos` condition the renderer is still active and producing frame. As a result this case is producing very noisy logs.
I'm changing that to debug for now to unblock next rc release, but in follow up I'll rework that code to warn if channel is closed but EOS was not sent yet.
> Do not warn on closed channel

- .github/workflows/package_for_release.yml
github actions changed what `macos-latest` means and it now uses M1 instance
> [ci] Fix macos x86_64 publish job

- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
The current implementation is not deterministic if you schedule events with the same PTS. This PR is enforcing a specific behavior. If events have the same PTS they will be executed in the same order that they were delivered.
> Enforce event order with the same PTS

- .github/workflows/check.yml
- .github/workflows/deploy_docs.yml
- .github/workflows/docker.yml
- .github/workflows/package_for_release.yml
- .github/workflows/shellcheck.yml
Closes #535 
Update deprecated actions
Add workflow_dispatch to docs deploy (sometimes we need to trigger manually)
> update deprecated github actions + add workflow dispatch to docs

- compositor_render/src/wgpu/ctx.rs
By splitting required_features into critical_features and nominal_mode_features and adding a bit of logic, let compositor start in a degraded mode on poor's man/hw instead of not running at all if it will affect only some functionalities of the compositor.
> Wgpu ctx init more laxist

- compositor_pipeline/src/queue/utils.rs
If EOS was received before first packet it never transitioned to Done state, so if stream was required it might block the queue indefinietlly.
> Handle EOS before first packet

- README.md
Firefox and older versions of Chrome don't support h265
> Demos recording fix h265 -> h264

- integration_tests/src/tests/schedule_update.rs
It is testing scheduled updates, so it's fine to make streams required without affecting what is tested
> Fix pottentially flaky integration test

- docs/src/pages/index.tsx
Addressing https://github.com/membraneframework/live_compositor/pull/590#discussion_r1634966646
I think listing email with that contatct us button would be wierd, so I removed button and made both links to be just texts. I'm not super happy how this looks, I'm open to other suggestions.
> [website] Update contact us section

- decklink/Cargo.toml
- decklink/src/api/profile.rs
It was not crashing, but according to docs some string attributes should not be freed.
> Some DeckLink profile attributes should not be freed

- compositor_pipeline/src/pipeline/input/decklink.rs
- compositor_pipeline/src/pipeline/input/decklink/capture.rs
- compositor_pipeline/src/pipeline/input/decklink/find_device.rs
- decklink/src/info.rs
- src/types/from_register_input.rs
- src/types/register_input.rs
- Add an option to specify the persistent id of the DeckLink device
- REST API expects hex string
- internally it's just an integer
- Error messages/responses will return string variant when no device is matched correctly
- Add an internal option to enforce pixel format (from REST API it is always forcing YUV422 8 bit)
- If the device supports 10-bit and 8-bit yuv it usually defaults to 10-bit which is not supported in compositor.
- If no DeckLink device is matched correctly, the error message will include a list of all Decklink devices
Example error message in case of mismatch
```
Error stack:
- Input initialization error while registering input for stream "input_1".
- No DeckLink device matches specified options. Found devices: [DeckLinkInfo { display_name: Some("DeckLink Quad HDMI …
```
> Select DeckLink by persistent ID + add override for pixel format

- compositor_pipeline/src/pipeline/input/decklink.rs
- compositor_pipeline/src/pipeline/input/decklink/capture.rs
When we force pixel format, the format changed notification is sent again after the first frame. To avoid that I'm recording previous format and only reset streams if the format should be changed
> Ignore DeckLink format changes if pixel format is forced

- integration_tests/Cargo.toml
Decklink example has to be run with a feature so we need to provide a way to pass it
> Fix decklink example (add missing feature)

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/input.rs
- compositor_pipeline/src/pipeline/input/decklink.rs
- compositor_pipeline/src/pipeline/input/mp4.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/pipeline/types.rs
- compositor_render/src/state/render_loop.rs
- compositor_render/src/wgpu.rs
- compositor_render/src/wgpu/ctx.rs
- compositor_render/src/wgpu/texture.rs
- compositor_render/src/wgpu/texture/base.rs
- compositor_render/src/wgpu/utils.rs
- compositor_render/src/wgpu/utils/r8_fill_value.wgsl
- compositor_render/src/wgpu/utils/r8_fill_with_color.rs
- integration_tests/examples/encoded_channel_output.rs
- integration_tests/examples/raw_channel_input.rs
- integration_tests/examples/raw_channel_output.rs
- integration_tests/src/lib.rs
- integration_tests/src/test_input.rs
- src/routes/register_request.rs
- Add input type that can take wgpu::Textures and raw audio
- Add example of using that input (video only)
> Add input type that returns data via channel

- docs/pages/guides/receive-output.md
Spotted missing part of command in docs while refactoring `examples` dir, so fixed it.
> [docs] Fix GStreamer receive UDP command

- docs/pages/guides/deliver-input.md
- docs/pages/guides/receive-output.md
Spotted issue with audio quality while testing receiving UDP with GStreamer, added corrected command to docs.
Added whole command instead of "replace with sth", to be easy to copy and do not require substituting some parts of original one.
> [docs] Updated GStreamer receive UDP command to ommit audio quality problems.

- CHANGELOG.md
- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/video_queue.rs
Steps to reproduce:
- start more than one stream when one of them is shorter than the others
- when the first stream is finished other streams might disappear
What happens:
- normally queue is
- checking if all inputs are ready (and pulling from channel if necessary)
- for each input:
- dropping old frames
- taking first frame (first not dropped should be the one we want to use)
- if one input is done without sending EOS, but just stops sending data
- checking if all inputs are ready is lazy, so if it checks that one specific input that ended it does not check any further
- for each input:
- dropping old frames will work, but because previous step did not enqueue new frames from the channel we are left with one outdated frame
- taking first frame return old frame (latter renderer can see …
> Fix input queueing when some of the inputs do not produce frames/samples

- compositor_pipeline/src/queue.rs
- integration_tests/Cargo.toml
- integration_tests/examples/aac_rtp_input.rs
- integration_tests/examples/decklink.rs
- integration_tests/examples/docker.rs
- integration_tests/examples/encoded_channel_output.rs
- integration_tests/examples/hls.rs
- integration_tests/examples/image.rs
- integration_tests/examples/mp4.rs
- integration_tests/examples/pass_through.rs
- integration_tests/examples/raw_channel_input.rs
- integration_tests/examples/raw_channel_output.rs
- integration_tests/examples/rtp_tcp.rs
- integration_tests/examples/samples_demo.rs
- integration_tests/examples/simple.rs
- integration_tests/examples/test_pattern.rs
- integration_tests/examples/text.rs
- integration_tests/examples/tiles.rs
- integration_tests/examples/transition.rs
- integration_tests/examples/web_view.rs
- integration_tests/src/examples.rs
- integration_tests/src/ffmpeg.rs
- integration_tests/src/gstreamer.rs
- integration_tests/src/lib.rs
issue https://github.com/membraneframework/live_compositor/issues/603 - examples dir refactor + cleanup
- added more general function for streaming with gstreamer and ffmpeg
- added possibility to stream any combination of video and audio using both gstreamer and ffmpeg
- added functions allowing for creating ffmpeg and gstreamer streams with predefined samples easily
> Add function simplifying creating new test examples

- compositor_api/src/types.rs
- compositor_api/src/types/from_register_output.rs
- compositor_api/src/types/register_output.rs
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline/encoder/opus.rs
- compositor_pipeline/src/pipeline/output.rs
- compositor_pipeline/src/pipeline/output/mp4.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_pipeline/src/pipeline/types.rs
- integration_tests/examples/mp4.rs
- src/routes/register_request.rs
The video output works fine.
Opus audio fails to write file trailer and logs an `invalid extradata size` error.
I'll implement an AAC encoder in another PR and test it after.
Merging:
I created the `@WojciechBarczynski/mp4` branch to which I'll merge all MP4 output-related PRs. Then I'll merge it to `master` without squashing. 
PRs adding AAC encoder, MP4 outputs, etc. are large enough to be separate PRs/commits, but I don't want to merge to master before testing it out.
> Video MP4 output

- generate/src/bin/generate_playground_inputs.rs
Simple script generating sample inputs for playground.
> add generating playground example input PNGs

- compositor_web/example/index.html
- compositor_web/src/wasm.rs
- compositor_web/src/wasm/input_uploader.rs
- compositor_web/src/wasm/output_downloader.rs
- compositor_web/src/wasm/types.rs
Currently wasm's `render` returns a map `OutputId => Bytes`. But, `render` method from `compositor_render` returns `FrameSet` which contains more additional information. In this PR I changed the wasm implimentation to also return `FrameSet`
> [wasm] Return `FrameSet` on render 

- compositor_render/src/event_handler.rs
There is a bug in the event_handler: the `Emitter` removes active subscribers instead of dead ones.
All the actually active subscribers will get an error when asking a message as their Sender was dropped.
> fix event handler: removing disconnected subscribers

- compositor_web/src/wasm/input_uploader.rs
- compositor_web/src/wasm/output_downloader.rs
The padding on output textures was not taken into account and the extra padding on input textures is not necessary
> [wasm] Fix texture size padding

- docs/src/api.ts
Default connection is set to production server, but if someone want to connect to local server they can do it by visiting `https://compositor.live/playground?local=true`
> [playground] Make connecting to local server possible

- build_tools/nix/flake.nix
- ts/@live-compositor/browser-render/package.json
- ts/@live-compositor/browser-render/rollup.config.mjs
- ts/@live-compositor/browser-render/scripts/buildWasm.mjs
- ts/@live-compositor/browser-render/tsconfig.json
- ts/package.json
- In the dist directory index.ts is generated for just index.d.ts, the section that should generate d.ts did not work. Type files were showing up only because `declaration: true`
- Node 20 is required to build wasm
- watch command should build with rollup not tsc
- Add `build-sdk` command to avoid building wasm when it is not needed
> [wasm] Fix bundler config

- integration_tests/src/tests/offline_processing.rs
The job on master failed with bitrate 986_000, so I'm updating this threshold
> [tests] Update offline processing integration test threshold

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- Stop queue when pipeline is dropped
- Do not hold to Arc<Pipeline> in render threads
Tested by creating pipeline and dropping it in the loop and observing memory usage
> Support pipeline shutdown

- .github/workflows/docker.yml
- build_tools/docker/full.Dockerfile
- build_tools/docker/slim.Dockerfile
> Update rust version in docker container

- compositor_web/src/wasm/input_uploader.rs
- compositor_web/src/wasm/types.rs
- ts/@live-compositor/browser-render/src/renderer.ts
Added YUV input format. Safari's implementation of `VideoDecoder` does not output RGBA but YUV420.
Closes: https://github.com/software-mansion/live-compositor/issues/746
> [wasm] Add YUV input

- docs/pages/api/inputs/decklink.md
- docs/pages/api/inputs/mp4.md
- docs/pages/api/inputs/rtp.md
- docs/pages/api/outputs/mp4.md
- docs/pages/api/outputs/rtp.md
PR for #752 
Added example requests to RTP/MP4/DeckLink pages to make going to HTTP Routes page not necessary.
Requests are split into two code blocks to make copying request json easier.
> [docs] Add example requests to API Reference

- CHANGELOG.md
- compositor_api/src/types/from_register_output.rs
- compositor_api/src/types/register_output.rs
- ts/live-compositor/src/types/registerOutput.ts
I don't have a strong option, but I noticed that the encoder field documentation was inconsistent with the implementation. We can make this field required and change docs instead. It's your call.
> Make encoder preset optional

- compositor_render/src/types.rs
- compositor_render/src/wgpu/format.rs
- compositor_render/src/wgpu/format/nv12_to_rgba.rs
- compositor_render/src/wgpu/format/nv12_to_rgba.wgsl
- compositor_render/src/wgpu/texture.rs
- compositor_render/src/wgpu/texture/nv12.rs
> Support input NV12 textures

- docs/pages/guides/basic-layouts.md
- docs/pages/guides/quick-start.md
- docs/pages/guides/view-transition.md
- docs/pages/intro.md
- docs/pages/intro/how-to-use.md
- docs/pages/intro/what-is-compositor.md
- docs/pages/intro/where-next.md
- docs/pages/typescript/api.md
- docs/pages/typescript/components/Image.md
- docs/pages/typescript/components/InputStream.md
- docs/pages/typescript/components/Shader.md
- docs/pages/typescript/components/WebView.md
- docs/pages/typescript/instance.md
- docs/sidebars.ts
- docs/src/components/ExampleSceneJsx.tsx
- docs/src/pages/index.tsx
- ts/live-compositor/src/components/common.ts
- Add React version of guides. It is not perfect there are still some places in those guides when we refer to input_id but it should be `inputId`, but reworking that would take to much time.
- Rework intro section to start promoting typescript as the primary way of using a compositor
- Add React code example to the main page
- changed `cubic-bezier` back to `cubic_bezier`. We don't rename other values (we rename only field names) so for consistency lets stay with underscore
> [docs] Rework getting started section + Add TypeScript

- vk-video/src/vulkan_decoder/vulkan_ctx.rs
Previously, vulkan debug layers were always activated when compiling in debug mode. Unfortunately, when a user compiled this library without having a separate package installed with the debug layers, it would fail to initialize because the lack of debug layers.
This patch only requests them if they are available on the system.
Closes #811
> Only request debug layers when they're available

- .github/workflows/macos_lint.yml
- Cargo.lock
- Cargo.toml
- compositor_pipeline/src/pipeline/graphics_context.rs
- compositor_pipeline/src/pipeline/input/rtp/depayloader.rs
- integration_tests/examples/manual_graphics_initialization.rs
- integration_tests/examples/vulkan.rs
> Add linting on macos

- compositor_render/src/transformations/layout/apply_layouts.wgsl
- compositor_render/src/transformations/layout/params.rs
- compositor_render/src/transformations/text_renderer.rs
- compositor_render/src/wgpu/common_pipeline.rs
- compositor_render/src/wgpu/format/interleaved_yuv_to_rgba.rs
- compositor_render/src/wgpu/format/nv12_to_rgba.rs
- compositor_render/src/wgpu/format/planar_yuv_to_rgba.rs
- compositor_render/src/wgpu/format/planar_yuv_to_rgba.wgsl
- compositor_render/src/wgpu/format/rgba_to_yuv.wgsl
- compositor_render/src/wgpu/texture/base.rs
- compositor_render/src/wgpu/texture/bgra.rs
- compositor_render/src/wgpu/texture/interleaved_yuv422.rs
- compositor_render/src/wgpu/texture/rgba.rs
- compositor_web/Cargo.toml
- compositor_web/src/wasm/input_uploader.rs
- integration_tests/examples/raw_channel_input.rs
- Fix passing output_resolution with WASM (alignment to 16 bytes)
- Switch all textures to srgb
Snapshots: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/46
> Switch to SRGB textures + add padding to outptu texture

- vk-video/src/parser.rs
- vk-video/src/parser/reference_manager.rs
- vk-video/src/vulkan_decoder.rs
Turns out these parts don't need to be done exactly according to the spec. The vulkan docs are not very clear on this unfortunately, but it seems to work.
> Remove spec-compliant reference picture list init and modification.

- integration_tests/src/tests/required_inputs.rs
I have seen some behavior that suggested that a combination of required: true and offset might not work correctly, so added some tests to verify that
> [tests] Add required audio stream snapshot tests

- CHANGELOG.md
- docs/pages/deployment/configuration.md
- generate/src/compositor_instance.rs
- integration_tests/examples/encoded_channel_output.rs
- integration_tests/examples/raw_channel_input.rs
- integration_tests/examples/raw_channel_output.rs
- integration_tests/examples/vulkan.rs
- integration_tests/src/compositor_instance.rs
- src/config.rs
- src/logger.rs
When the compositor is run deep inside some other solution it is sometimes hard to get logs from it. Add file logger should solve that problem
> Add file logger

- src/snapshot_tests.rs
- src/snapshot_tests/test_case.rs
- src/snapshot_tests/utils.rs
- src/snapshot_tests/yuv_tests.rs
- src/snapshot_tests/yuv_tests/gradient.wgsl
Initially, I wanted to improve how YUV conversion affects the output, particularly in the case of smooth color changes. It's very visible (see image bellow).
This PR does not fix anything, but when debugning I added some usefull utils for testing:
- You can now write snapshot tests for RGBA textures before YUV conversion (to verify if potential artifacts are the result of YUV conversion or rendering)
- Add 2 tests that show how much YUV conversion back and forth affects the values
> [tests] Add tests that verify YUV conversion

- .github/workflows/ts_sdk_check.yml
- compositor_web/Cargo.toml
- ts/package.json
There is some regression around version of Rust and wasm-bindgen that is causin `Result` type to be converted to `Array`
> [ts-sdk] Fix WASM types generation

- Cargo.lock
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder/video/vulkan_video.rs
- compositor_pipeline/src/pipeline/graphics_context.rs
- compositor_render/src/lib.rs
- compositor_render/src/wgpu.rs
- compositor_render/src/wgpu/ctx.rs
- integration_tests/examples/manual_graphics_initialization.rs
- integration_tests/examples/raw_channel_input.rs
- integration_tests/examples/raw_channel_output.rs
- integration_tests/examples/vulkan.rs
- src/snapshot_tests/utils.rs
- vk-video/Cargo.toml
- vk-video/examples/basic.rs
- vk-video/examples/player/main.rs
- vk-video/examples/player/player.rs
- vk-video/examples/player/player/decoder.rs
- vk-video/examples/player/player/renderer.rs
- vk-video/examples/player/player/shader.wgsl
- vk-video/examples/wgpu.rs
- vk-video/src/lib.rs
- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/session_resources.rs
- vk-video/src/vulkan_decoder/session_resources/images.rs
- vk-video/src/vulkan_decoder/session_resources/parameters.rs
- vk-video/src/vulkan_decoder/vulkan_ctx.rs
- vk-video/src/vulkan_decoder/wrappers/video.rs
This change allows users to initialize `vk-video` with wgpu surfaces for rendering to an on-screen window. This was previously overlooked and there was no possibility to guarantee a `VulkanCtx` was able to render on screen.
This patch also adds an example h264 player to vk-video.
Closes #821.
> New architecture for vk-video initialization.

- Cargo.lock
- compositor_chromium/chromium_sys/Cargo.toml
- compositor_chromium/chromium_sys/build.rs
Most of the CEF build time is spent on actually downloading CEF itself which happens every time `OUT_DIR` changes. I moved the default `cef_root` to `~/.cache` which helps with the recompilation a lot (less than 1s).
> Download CEF binaries to `~/.cache`

- build_tools/nix/flake.lock
- compositor_pipeline/src/pipeline/decoder/audio/opus.rs
Not sure if it related to Rust update, but audio decoder is failing for me on master. Moving OPUS buffer to heap seems to fix it
> Move OPUS decoder buffer to heap

- build_tools/nix/flake.nix
- build_tools/nix/package.nix
- ts/@live-compositor/core/src/api.ts
- ts/@live-compositor/core/src/compositorManager.ts
- ts/@live-compositor/core/src/event.ts
- ts/@live-compositor/core/src/index.ts
- ts/@live-compositor/core/src/live/compositor.ts
- ts/@live-compositor/core/src/live/output.ts
- ts/@live-compositor/core/src/offline/compositor.ts
- ts/@live-compositor/core/src/offline/output.ts
- ts/@live-compositor/core/src/renderer.ts
- ts/@live-compositor/core/tsconfig.cjs.json
- ts/@live-compositor/node/src/index.ts
- ts/@live-compositor/node/src/manager/existingInstance.ts
- ts/@live-compositor/node/src/manager/locallySpawnedInstance.ts
- ts/examples/node-examples/src/combine_mp4.tsx
- ts/examples/node-examples/src/concat_mp4.tsx
- ts/live-compositor/src/components/Show.ts
- ts/live-compositor/src/components/SlideShow.ts
- ts/live-compositor/src/components/Slides.ts
- ts/live-compositor/src/context/audioOutputContext.ts
- ts/live-compositor/src/context/childrenLifetimeContext.ts
- ts/live-compositor/src/context/index.ts
- ts/live-compositor/src/context/timeContext.ts
- ts/live-compositor/src/hooks.ts
- ts/live-compositor/src/index.ts
- ts/live-compositor/src/internal.ts
- ts/package.json
- ts/pnpm-lock.yaml
- Add `Slides`/`Slide` components
- Add `Show` component
- Add the `useAfterTimestamp` hook (internally used by `Show`)
- Add `useCurrentTimestamp` returns the current timestamp (does not trigger re-render for every time change)
- Alternative 1:  Add a hook that returns a function that returns a timestamp
- Alternative 2: Add a hook that returns some context object that has a method that returns a timestamp
- Alterantive 3: Do not expose it, but instead make `useAfterTimestamp` return the current timestamp (and maybe change name of that hook)
- Add `useBlockingTask` hook
- For live cases run the async function on mount. Hook returns result if promise resolved or undefined otherwise
- Similiar to https://react.dev/reference/react/use
- For offline cases it blocks rendering until promise …
> [ts-sdk] Add offline processing

- compositor_web/src/wasm.rs
- compositor_web/src/wasm/types.rs
- ts/@live-compositor/browser-render/src/renderer.ts
- ts/@live-compositor/core/package.json
- ts/@live-compositor/core/src/compositorManager.ts
- ts/@live-compositor/core/src/event.ts
- ts/@live-compositor/core/src/index.ts
- ts/@live-compositor/core/src/live/compositor.ts
- ts/@live-compositor/core/src/live/output.ts
- ts/@live-compositor/core/src/logger.ts
- ts/@live-compositor/core/src/offline/compositor.ts
- ts/@live-compositor/core/src/offline/output.ts
- ts/@live-compositor/core/src/renderer.ts
- ts/@live-compositor/core/src/utils.ts
- ts/@live-compositor/node/package.json
- ts/@live-compositor/node/src/index.ts
- ts/@live-compositor/node/src/logger.ts
- ts/@live-compositor/node/src/manager/existingInstance.ts
- ts/@live-compositor/node/src/manager/locallySpawnedInstance.ts
- ts/@live-compositor/node/src/spawn.ts
- ts/@live-compositor/node/src/ws.ts
- ts/@live-compositor/web-wasm/package.json
- ts/@live-compositor/web-wasm/src/compositor.ts
- ts/live-compositor/src/context/index.ts
- ts/live-compositor/src/context/inputStreamStore.ts
- ts/live-compositor/src/context/timeContext.ts
- ts/live-compositor/src/internal.ts
- ts/live-compositor/src/types/logger.ts
- ts/pnpm-lock.yaml
I keep adding and removing console logs when debuging, so I added a structured logging library to leave some useful logs in place without spamming users.
I also adjusted the defaults for logging especially for wasm. I want logger configuration to be exposed to user somehow eventually, but for now this is only intended for our use
> [ts-sdk] Add logger

- ts/@live-compositor/node/README.md
- ts/live-compositor/README.md
- ts/live-compositor/src/component.ts
- ts/live-compositor/src/components/Image.ts
- ts/live-compositor/src/components/InputStream.ts
- ts/live-compositor/src/components/Rescaler.ts
- ts/live-compositor/src/components/Shader.ts
- ts/live-compositor/src/components/Show.ts
- ts/live-compositor/src/components/SlideShow.ts
- ts/live-compositor/src/components/Text.ts
- ts/live-compositor/src/components/Tiles.ts
- ts/live-compositor/src/components/View.ts
- ts/live-compositor/src/components/WebView.ts
[#899](https://github.com/software-mansion/live-compositor/issues/899)
> Update sdk types

- ts/@live-compositor/web-wasm/src/input/input.ts
- ts/@live-compositor/web-wasm/src/input/inputFrameProducer.ts
- ts/@live-compositor/web-wasm/src/input/mp4/demuxer.ts
- ts/@live-compositor/web-wasm/src/input/mp4/source.ts
- ts/@live-compositor/web-wasm/src/input/producer/decodingFrameProducer.ts
- ts/@live-compositor/web-wasm/src/input/source.ts
- ts/@live-compositor/web-wasm/src/manager/wasmInstance.ts
- ts/@live-compositor/web-wasm/src/queue.ts
- ts/examples/vite-browser-render/src/examples/MP4Player.tsx
- ts/pnpm-lock.yaml
The current `Input` implementation assumed that every input type will have a similar frame production and frame buffering strategy. That approach does not work well with camera and share-screen input. This PR makes it possible to add different strategies for frame production.
- Each frame producer has to implement `InputFrameProducer` interface.
- `DecodingFrameProducer` accepts any `InputSource` (Encoded chunk producer). It produces frames from encoded chunks and handles the frame buffering.
- The future input types such as `Camera` & `Share screen` will require different implementation of `InputFrameProducer` which  accepts `MediaStream` and does no buffering.
> [web-wasm] Decouple frame production from input implementation

- ts/@live-compositor/web-wasm/src/input/mp4/demuxer.ts
- ts/@live-compositor/web-wasm/src/input/producer/decodingFrameProducer.ts
According to the spec, chunks should use microseconds instead of milliseconds.
Tested on:
- http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4
- https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4
- https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
> [web-wasm] Fix incorrent chunk timestamps

- Cargo.lock
- vk-video/Cargo.toml
- vk-video/examples/player/player/shader.wgsl
- vk-video/src/parser/nalu_splitter.rs
- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/session_resources.rs
- vk-video/src/vulkan_decoder/vulkan_ctx.rs
- vk-video/src/vulkan_decoder/wrappers/command.rs
- vk-video/src/vulkan_decoder/wrappers/parameter_sets.rs
This PR fixes a couple bugs I found by accident in the hardware decoder.
1. Splitting the bytestream into NAL units was taking 80% of the decoding time, even though it's just a simple sequence search. I replaced my naive implementation with the [memchr crate](https://crates.io/crates/memchr).
2. I never realized the frame cropping h264 feature was very important. Turns out we cannot really decode 1920x1080 video without it, because 1080 is not divisible by 16. I implemented this correctly.
3. Also fixed some bugs related to dropping.
4. The player in the vk-video example now uses same numbers as ffmpeg for color conversion.
> Fix a couple of bugs in the hardware decoder.

- .github/workflows/package_for_release.yml
- scripts/release.sh
Example multi-platform builds:
- slim: https://github.com/software-mansion/live-compositor/pkgs/container/smelter/333356027?tag=test5
- web-renderer: https://github.com/software-mansion/live-compositor/pkgs/container/smelter/333354551?tag=test5-web-renderer
> Publish arm docker images as part of the release process

- Cargo.lock
- compositor_pipeline/src/pipeline/graphics_context.rs
- integration_tests/Cargo.toml
- integration_tests/src/bin/benchmark/args.rs
- integration_tests/src/bin/benchmark/main.rs
- vk-video/src/lib.rs
- vk-video/src/vulkan_decoder/vulkan_ctx.rs
Here's an initial benchmarking setup. For context, the end goal for this is for us to be able to run a set of these benchmarks on any computer and figure out what kind of smelter setups can be run on it. 
You can run it with:
```sh
cargo run --bin benchmark -- --help
```
to get the information on how to run a single test.
The full command is quite verbose, and looks like this:
```sh
cargo run --release --bin benchmark -- \
--framerate 24 \
--decoder-count maximize \
--file-path examples/assets/BigBuckBunny.mp4 \
--output-width 1280 \
--output-height 720 \
--encoder-preset ultrafast \
--warm-up-time 10 \
--measured-time 10 \
--video-decoder vulkan_video_h264 \
--framerate-tolerance 1.05
```
The help message will tell you all of the options for each of the arguments.
It can currently run a …
> Add initial benchmarking setup.

- Cargo.lock
- vk-video/Cargo.toml
- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/session_resources/parameters.rs
- vk-video/src/vulkan_decoder/wrappers/parameter_sets.rs
The new version includes handling scaling lists, so this patch also handles them correctly in our decoder. Unfortunately I'm unable to find any h264 videos that use scaling lists, so this is untested, but I figure if it doesn't work somebody will sooner or later come to us with an issue.
This brings us one step closer to releasing vk-video, since this removes the last git-based dependency.
Closes #859
> Update to the new version of `h264_reader`.

- compositor_pipeline/src/pipeline/output/whip.rs
- compositor_pipeline/src/pipeline/output/whip/establish_peer_connection.rs
- compositor_pipeline/src/pipeline/output/whip/init_peer_connection.rs
- integration_tests/examples/whip_client.rs
PR for issue #923 
- modified location header parsing
- fixed trickle ice sdp structure (works with vdo.ninja)
- fixed problem with duplicating codec--payload-type mappings in sdp offer (registering supported subset of default codecs)
> Fix WHIP output

- src/routes/unregister_request.rs
- ts/smelter-core/src/api.ts
- ts/smelter-core/src/live/compositor.ts
- ts/smelter-core/src/live/output.ts
- ts/smelter-core/src/offline/output.ts
- ts/smelter/src/components/Image.ts
- ts/smelter/src/components/Mp4.ts
- The rust server did not support scheduling image unregister which is necessary for the offline cases (or we could skip unregisters entirely)
- path field was not passed through the request
- Types for Mp4 and Image request were incorrect (as a fix I changed values to match, not types)
- Move `newBlocikngTask` just before the try-catch (if an exception would throw on asset type it would block rendering indefinitely
Tested on meetup example
> Fix image autoregister

- ts/smelter-browser-render/src/wasm.ts
It's a potential fix for https://github.com/software-mansion/smelter/issues/874
When wasm module is loaded more than once it can override the wasm's internals. I tested it on `wgpu 24.0.1`  MacOS / Linux and it seems to be working
> [web-wasm] Ensure wasm module is loaded only once

- compositor_api/src/types/from_component.rs
text renderirng panics on zero line height, validate it on the api layer
> Validate if line_height is set to zero

- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/output.rs
This removes the annoying ffmpeg warning that usually shows up about MB rate being higher than level limit.
> Pass framerate to the encoder when it's being created.

- compositor_api/src/types/from_component.rs
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/shader/validation.rs
- compositor_render/src/transformations/shader/validation/shader_header_web.wgsl
- compositor_web/src/wasm.rs
- compositor_web/src/wasm/renderer.rs
- compositor_web/src/wasm/types.rs
- ts/examples/vite-example/src/App.tsx
- ts/examples/vite-example/src/smelter-examples/ShaderExample.tsx
- ts/smelter-browser-render/src/api.ts
- ts/smelter-browser-render/src/renderer.ts
- ts/smelter-web-wasm/src/compositor/api.ts
- ts/smelter-web-wasm/src/compositor/compositor.ts
- ts/smelter-web-wasm/src/mainContext/instance.ts
- ts/smelter-web-wasm/src/workerApi.ts
- ts/smelter-web-wasm/src/workerContext/pipeline.ts
- ts/smelter-web-wasm/src/workerContext/runWorker.ts
Shaders on web have to be slightly different from the native version, because we can't use `binding_array` on web.
Due to those limitations, on the web, we'll only allow one texture to be passed to the user shader
Closes: #701
> [ts-sdk] Make shaders work on web

- ts/smelter-core/src/api/input.ts
- ts/smelter-web-wasm/src/compositor/api.ts
- ts/smelter-web-wasm/src/mainContext/input.ts
- ts/smelter-web-wasm/src/mainContext/input/mp4.ts
- ts/smelter/src/components/Mp4.ts
- ts/smelter/src/types/registerInput.ts
> [ts-sdk] Add `Blob` as MP4 input

- CHANGELOG.md
- compositor_chromium/src/settings.rs
- compositor_render/src/transformations/web_renderer.rs
- compositor_render/src/transformations/web_renderer/chromium_context.rs
- compositor_render/src/transformations/web_renderer/chromium_sender_thread.rs
- compositor_render/src/transformations/web_renderer/renderer.rs
- compositor_render/src/transformations/web_renderer/utils.rs
When two instances of smelter share the same CEF `root_cache_path`, one instance becomes the main browser window, and the other acts as an opened "tab" in that browser. We don't handle that case at all, hence the crash. Fixed it by giving each instance a unique `root_cache_path` so now each instance works independently. 
Fixes: #1014
> Fix web renderer crashing when multiple Smelter instances are run

- compositor_pipeline/src/pipeline/decoder/audio.rs
- compositor_pipeline/src/pipeline/decoder/video.rs
- compositor_pipeline/src/pipeline/decoder/video/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/decoder/video/ffmpeg_vp8.rs
- compositor_pipeline/src/pipeline/decoder/video/vulkan_video.rs
- compositor_pipeline/src/pipeline/input.rs
- Prevent resetting pts to zero in audio and video decoder.
- Add a send_eos flag, allowing control over whether eos is sent to the queue. This is needed for WHIP input to be able to reconnect to the same input without dropping the queue."
> Prevent decoder from resetting PTS, add flag `send_eos`

- integration_tests/src/tests/unregistering.rs
The test is failing periodically because we try to register output twice on the same port. The first attempt is supposed to fail, but the port is blocked for a bit until the system allows to bind to it. As a result, second attempt is often failing because of that
> Fix flaky test

- compositor_api/src/types/from_register_output.rs
- compositor_api/src/types/register_output.rs
- ts/create-smelter-app/templates/node-express-zustand/src/smelter.tsx
- ts/create-smelter-app/templates/node-express-zustand/src/smelterFfplayHelper.ts
- ts/create-smelter-app/templates/node-minimal/src/index.tsx
- ts/create-smelter-app/templates/node-minimal/src/smelterFfplayHelper.ts
- ts/examples/node-examples/src/audio.tsx
- ts/examples/node-examples/src/dynamic-inputs.tsx
- ts/examples/node-examples/src/dynamic-outputs.tsx
- ts/examples/node-examples/src/dynamic-text.tsx
- ts/examples/node-examples/src/simple.tsx
- ts/examples/node-examples/src/utils.ts
- ts/examples/node-examples/src/web-view.tsx
- ts/smelter-core/src/api/output.ts
- ts/smelter-core/src/api/output/rtmp.ts
- ts/smelter-node/src/api.ts
- ts/smelter-node/src/live/compositor.ts
- ts/smelter-node/src/offline/compositor.ts
- ts/smelter/src/api.generated.ts
- ts/smelter/src/index.ts
- ts/smelter/src/types/output.ts
- ts/smelter/src/types/output/rtmp.ts
Rust
- Few type renames
- change default sample rate for RTMP
JS
- Add types
- switch templates and examples to use RTMP instead of RTP
> [ts-sdk] Add RTMP output + update examples

- compositor_api/src/types/from_util.rs
- compositor_api/src/types/util.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/rescaler_component.rs
- compositor_render/src/scene/tiles_component.rs
- compositor_render/src/scene/transition.rs
- compositor_render/src/scene/types.rs
- compositor_render/src/scene/view_component.rs
- schemas/scene.schema.json
- ts/smelter/src/api.generated.ts
- ts/smelter/src/components/common.ts
The behaviour on scene update:
- If component props changed between updates
- If `should_interrupt` flag is `true`, new transition is started
- If there is a transition already in progress, it's continued, but the destination is changed
- otherwise, new transition is started
- otherwise, no new transition is applied
Snapshots PR: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/56
Closes #1019
> Prevent transitions from resetting on update

- .cargo/config.toml
- Cargo.lock
- compositor_web/Cargo.toml
- compositor_web/src/wasm.rs
- compositor_web/src/wasm/input_uploader.rs
- compositor_web/src/wasm/output_downloader.rs
- compositor_web/src/wasm/renderer.rs
- compositor_web/src/wasm/types.rs
- ts/examples/vite-example/src/renderer-examples/Counter.tsx
- ts/smelter-browser-render/src/renderer.ts
- ts/smelter-web-wasm/src/workerContext/input/MediaStreamInput.ts
- ts/smelter-web-wasm/src/workerContext/input/QueuedInput.ts
- ts/smelter-web-wasm/src/workerContext/input/frame.ts
- ts/smelter-web-wasm/src/workerContext/input/input.ts
- ts/smelter-web-wasm/src/workerContext/input/videoDecoder.ts
- ts/smelter-web-wasm/src/workerContext/output/canvas.ts
- ts/smelter-web-wasm/src/workerContext/output/output.ts
- ts/smelter-web-wasm/src/workerContext/output/sink.ts
- ts/smelter-web-wasm/src/workerContext/queue.ts
- ts/smelter-web-wasm/src/workerContext/runWorker.ts
Tested on Chrome and Safari. This PR improved performance only on macOS. The approach used here actually makes the performance worse on most platforms (except macOS, probably due to the fact that CPU and GPU share the same memory on  macs)
Closes #1034
> [web-wasm] Reduce number of input frame copies

- compositor_api/src/types/from_register_output.rs
- compositor_api/src/types/register_output.rs
- integration_tests/examples/aac_rtp_input.rs
- integration_tests/examples/audio.rs
- integration_tests/examples/decklink.rs
- integration_tests/examples/mp4_output.rs
- integration_tests/examples/rtmp_output.rs
- integration_tests/examples/rtp_tcp.rs
- integration_tests/examples/samples_demo.rs
- integration_tests/examples/whip_client.rs
- integration_tests/examples/whip_server.rs
- integration_tests/src/tests/audio_only.rs
- integration_tests/src/tests/offline_processing.rs
- integration_tests/src/tests/required_inputs.rs
- integration_tests/src/tests/video_audio.rs
Make audio channels (Mono/Stereo) option for audio output, not specific for each audio encoder.
> Refactor output audio api, move `channels` from encoder options to audio options

- .github/workflows/lint.yml
- .github/workflows/macos_lint.yml
- .github/workflows/test.yml
- .github/workflows/ts_sdk_check.yml
- .github/workflows/wasm.yml
- ts/smelter-node/src/live/compositor.ts
- ts/smelter-node/src/offline/compositor.ts
Temporary fix, due to the inability to get a bearer_token while using WHIP input in the ts-sdk. Modifications in smelter-core api will be needed for right solution
> Make `registerInput` return value in `smelter-node`

- compositor_web/src/lib.rs
- compositor_web/src/types.rs
- compositor_web/src/wasm.rs
- compositor_web/src/wasm/input.rs
- compositor_web/src/wasm/output.rs
- compositor_web/src/wasm/renderer.rs
- compositor_web/src/wasm/types.rs
- ts/smelter-browser-render/src/renderer.ts
- ts/smelter-web-wasm/src/workerContext/queue.ts
- ts/smelter-web-wasm/src/workerContext/runWorker.ts
- Seprate binding layer from internal implementation
- Handle a case where `frame` is `HTMLVideoElement` (there is still some issue with that, output color space seems to be incorrect, but I'll verify that in follow up PRs that are using that feature)
> [ts-sdk] Refactor WASM types + add HTMLVideoElement as input

- vk-video/.gitignore
- version in `Cargo.toml` is set to 0.1.0
- adding rawvideo files to gitignore
> [vk-video] Release `0.1.0`

- Cargo.lock
- compositor_render/Cargo.toml
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/shader/validation.rs
- compositor_render/src/transformations/shader/validation/error.rs
- compositor_render/src/wgpu/ctx.rs
wgpu reexports `naga` now. This patch makes our code use this reexported `naga` instead of having it as a separate dependency. This saves us the trouble of syncing the naga and wgpu versions every time we update wgpu.
> Use `naga` from wgpu instead of having it as a separate dependency

- .github/workflows/rust_check.yml
The rust cache now works properly which speeds up the compilation time. However, running tests is still the largest bottleneck by far.
Closes: #1161
> Make CI faster

- compositor_api/src/input/whip.rs
- compositor_api/src/input/whip_into.rs
- compositor_pipeline/src/pipeline/webrtc/server.rs
- compositor_pipeline/src/pipeline/webrtc/server/create_whip_session.rs
- compositor_pipeline/src/pipeline/webrtc/server/new_whip_ice_candidates.rs
- compositor_pipeline/src/pipeline/webrtc/server/terminate_whip_session.rs
- compositor_pipeline/src/pipeline/webrtc/whip_input.rs
- compositor_pipeline/src/pipeline/webrtc/whip_input/connection_state.rs
- compositor_pipeline/src/pipeline/webrtc/whip_input/state.rs
- compositor_pipeline/src/pipeline/webrtc/whip_input/track_audio_thread.rs
- compositor_pipeline/src/pipeline/webrtc/whip_input/track_video_thread.rs
- compositor_pipeline/src/protocols/webrtc.rs
- ts/smelter-core/src/api/input.ts
- ts/smelter/src/api.generated.ts
Ensures WHIP sessions on a single input are uniquely identified, preventing a disconnected client from sending a `DELETE` that affects another active session.
> Distinguish WHIP sessions on a single input

- ts/smelter/src/components/Rescaler.ts
- ts/smelter/src/components/View.ts
- ts/smelter/src/components/common.ts
Map `BoxShadow` type to `camelCase` in `ts-sdk`
> [ts-sdk] Add `BoxShadow` type

- build_tools/docker/full.Dockerfile
- build_tools/docker/slim.Dockerfile
Current dockerfiles do not build correctly because rust is to old for some packages
> Bump version in Dockerfile

- ts/smelter/src/types/refs/imageRef.ts
- ts/smelter/src/types/refs/inputRef.ts
Inputs with colons were not handled correctly because join by default was replacing `:` with `,`
> [ts-sdk] Fix inputs with colons in the name

- ts/smelter/src/context/audioOutputContext.ts
Before this change, inputs were never removed. As a result update request included old (already unregistered inputs) with volume set to zero.
It's not causing any invalid behavior, but in time it could grow to large amount of data that needs to be sent on every update.
> [ts-sdk] Remove audio streams from context

- compositor_pipeline/src/pipeline/resampler/dynamic_resampler.rs
The output sample rate was incorrect, resulting in the incorrect end_pts value for batches in the mixer. The audio mixer  mostly relies on the sample rate value globally defined, so even with this bug it worked in general because the end_pts value of the batch is not used for most of the calculations
> Fix returned sample rate value in resampler

- integration_tests/examples/demo/main.rs
- integration_tests/examples/demo/smelter_state.rs
- integration_tests/src/examples.rs
Simple error handling for client requests.
Additionally handled situation when server is not running (inside of `examples.rs` file).
> [examples] Added error handling for register and unregister requests.

- integration-tests/src/bin/generate_frequencies.rs
- integration-tests/src/pipeline_tests/audio_only.rs
> [integration-tests] Added new audio tests.
