software-mansion/smelter

- Cargo.lock
- compositor_render/Cargo.toml
- compositor_render/src/lib.rs
- compositor_render/src/renderer.rs
For now this crate contains a basic test, which should check whether we are able to establish a connection to the GPU (also the emulated GPU on CI)
> Add a new `compositor_render` crate.

- Cargo.lock
- Cargo.toml
- compositor_pipeline/Cargo.toml
- compositor_pipeline/src/pipeline.rs
- examples/simple_ffmpeg.rs
- src/http.rs
- src/main.rs
- src/rtp_receiver.rs
- src/rtp_sender.rs
Replace println!/eprintln! with env_logger
> Add env_logger

- .github/workflows/node.yml
- web_renderer/.eslintrc.json
- web_renderer/.prettierrc
- web_renderer/forge.config.ts
- web_renderer/package-lock.json
- web_renderer/package.json
- web_renderer/src/index.ts
- web_renderer/src/schemas.ts
- web_renderer/src/server.ts
- web_renderer/src/session.ts
- web_renderer/webpack.main.config.ts
- web_renderer/webpack.plugins.ts
- web_renderer/webpack.renderer.config.ts
- web_renderer/webpack.rules.ts
Some of the files had inconsistent indentation and formatting in general. Added prettier and rerun eslint (eslint is triggering prettier)
> add prettier

- examples/long_ffmpeg.rs
> Fix long_ffmpeg example

- design_docs/2023_08_02_shader_parameter_format.md
I need some feedback before I start implementing this
> Shader parameter json format design doc

- compositor_render/src/renderer.rs
- compositor_render/src/transformations/text_renderer.rs
According to: https://docs.rs/cosmic-text/latest/cosmic_text/index.html swash cache also should be created only once
> Move swash cache to text renderer ctx

- Cargo.lock
- Cargo.toml
- compositor_common/src/scene.rs
- compositor_common/src/validators/test.rs
- compositor_render/Cargo.toml
- compositor_render/examples/silly.wgsl
- compositor_render/examples/silly_shader.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/transformations/shader/node.rs
- examples/docker.rs
- examples/long_ffmpeg.rs
- examples/simple_ffmpeg.rs
This patch allows shaders that don't take custom parameters.
Closes #12, finally
> Add shaders without user-defined parameters.

- Cargo.lock
- Cargo.toml
- compositor_common/src/scene.rs
- compositor_common/src/transformation.rs
- compositor_render/Cargo.toml
- compositor_render/src/registry.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/renderer/texture/rgba.rs
- compositor_render/src/sync_renderer.rs
- compositor_render/src/transformations.rs
- compositor_render/src/transformations/image_renderer.rs
- examples/image.rs
Supports:
- PNG
- JPEG
- GIF(only as static image)
- SVG(subset of SVG supported by resvg)
> Add support for static images

- compositor_render/src/transformations/shader.rs
Empty textures are created for every render, so I moved that from the render function.
I looked into optimizing other parts that are created per frame, but I suspect we can't easily optimize it. `input_textures_bg` is created based on inputs and those can change on every render e.g. because resolution changed. We could maybe keep track of what was used for previous renders and cache that, but this seems a bit hacky, so unless it's the source of performance issues I would prefer to avoid it.
Nothing is logged anymore by wgpu, so I suspect this was only part that shouldn't be done per frame.
> Stop creating textures every frame

- compositor_render/src/renderer.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/sync_renderer.rs
- compositor_render/src/transformations/image_renderer.rs
- examples/image.rs
Create separate textures for each frame and add hard coded limit to max 1000 frames.
> Add support for animated GIFs

- compositor_render/src/render_loop.rs
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/renderer/texture.rs
- compositor_render/src/transformations/image_renderer.rs
- compositor_render/src/transformations/shader/node.rs
- compositor_render/src/transformations/text_renderer.rs
- compositor_render/src/transformations/web_renderer.rs
> Scene without arcs

- compositor_chromium/chromium_sys/build.rs
> Fix cef download

- compositor_chromium/chromium_sys/build.rs
> Fix CEF download for real

- compositor_pipeline/src/error.rs
- compositor_pipeline/src/lib.rs
- compositor_pipeline/src/pipeline.rs
- src/api.rs
- src/error.rs
- src/http.rs
- src/lib.rs
- src/main.rs
Rework top-level errors to provide a bit more user-friendly error to user.
I left 3 most problematic errors for follow up PR
> Improve error handling - part 1

- compositor_pipeline/src/error.rs
- examples/image.rs
gif, jpeg, png and svg example
> Add image examples + cleanup failing asset downloads

- Cargo.lock
- compositor_render/Cargo.toml
- compositor_render/src/renderer.rs
- compositor_render/src/renderer/renderers.rs
- compositor_render/src/transformations/builtin/transformations.rs
- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/shader/validation.rs
- compositor_render/src/transformations/shader_header.wgsl
This PR adds validation to user-provided shaders. It checks whether the user has declared global variables with the same type and binding information as the ones we're passing to them and the correctness of the vertex shader argument type.
I want to add input validation to those custom shaders in a subsequent PR
> Shader validation part 1

- compositor_render/src/renderer.rs
- compositor_render/src/renderer/node.rs
- compositor_render/src/renderer/scene.rs
- compositor_render/src/transformations/builtin/node.rs
- compositor_render/src/transformations/shader.rs
- compositor_render/src/transformations/shader/error.rs
- compositor_render/src/transformations/shader/node.rs
- compositor_render/src/transformations/shader/pipeline.rs
- compositor_render/src/transformations/shader/validation.rs
This PR adds user parameter typechecking
closes #95
> User params validation

- compositor_common/src/error.rs
- compositor_common/src/scene/builtin_transformations.rs
- compositor_render/src/transformations/builtin/params/fixed_position_layout.rs
- examples/image.rs
Add bottom/right options to the fixed position layout component
Add labels to image examples
> Add right/bottom options to layout component

- compositor_common/src/scene/builtin_transformations.rs
- compositor_render/src/transformations/builtin.rs
- compositor_render/src/transformations/builtin/error.rs
- compositor_render/src/transformations/builtin/mirror_image.wgsl
- compositor_render/src/transformations/builtin/node.rs
- compositor_render/src/transformations/builtin/params.rs
- compositor_render/src/transformations/builtin/params/mirror_image.rs
- compositor_render/src/transformations/builtin/transformations.rs
- examples/builtin_transformations.rs
- Add mirror image transformation with option to flip input vertically or horizontally
- default to horizontal
- output resolution is dynamic and depends on input resolution
> Add mirror-image transformation

- src/rtp_receiver.rs
- src/rtp_sender.rs
All resolutions (divisible by 2) should work now.
> Take stride into account when copying data to/from AV frames.

- compositor_common/src/scene/builtin_transformations.rs
- compositor_common/src/scene/text_spec.rs
- compositor_common/src/util/align.rs
- compositor_render/src/transformations/builtin.rs
- compositor_render/src/transformations/builtin/box_layout.rs
- compositor_render/src/transformations/builtin/params.rs
- compositor_render/src/transformations/builtin/params/tiled_layout.rs
- compositor_render/src/transformations/builtin/params/transform_to_resolution.rs
- examples/builtin_transformations.rs
Rewrites fit transformation. Adds horizontal and vertical align to fit to resolution
> Fit align params

- Cargo.lock
- Cargo.toml
- compositor_pipeline/Cargo.toml
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/encoder.rs
- src/api.rs
- src/rtp_sender.rs
I will add better error handling in a subsequent PR. I also plan to extract the decoders in a similar way later.
> Extract the encoder from the rtp sender into the pipeline.

- Dockerfile
- docker/entrypoint.sh
- examples/docker.rs
- examples/web_renderer.rs
Fix docker example
I also tested a web renderer, but it still does not work.
> Fix docker example

- compositor_common/src/error.rs
- compositor_pipeline/src/queue/internal_queue.rs
- compositor_render/src/renderer/texture.rs
New clippy version, new errors ¯\_(ツ)_/¯
> Fix new clippy errors

- compositor_render/src/transformations/text_renderer.rs
> Fix letters cutting in text rendering

- .github/workflows/rust.yml
- compositor_common/src/scene/constraints.rs
- compositor_pipeline/src/pipeline/encoder.rs
- examples/image.rs
- schemas/register.schema.json
- schemas/scene.schema.json
- src/api.rs
- src/bin/generate_json_schema.rs
- src/error.rs
- src/types.rs
- src/types/convert.rs
- src/types/convert_util.rs
- src/types/from_node.rs
- src/types/from_renderer.rs
- src/types/register_request.rs
- src/types/renderer.rs
- src/types/util.rs
- No (intended) API changes
- Replace anyhow::Error with TypeError to avoid
`map_err(|err: anyhow::Error| ApiError::malformed_request(err.as_ref()))?,` in a lot of places
> JSON schema for register requests

- .gitattributes
- schemas/scene.schema.json
- src/bin/generate_json_schema.rs
Issue described inside a comment
> Fix schema

- examples/builtin_transformations.rs
- examples/image.rs
- schemas/scene.schema.json
- snapshot_tests/basic_scene.json
- src/types/from_node.rs
- src/types/into_node.rs
- src/types/node.rs
This is only changes to API, similar changes would be useful in the internal implementation
> Split transform_to_resolution node

- src/snapshot_tests/test_case.rs
- Produce `png` instead of `bmp`
- Slightly better checking for unused snapshots (I intend to rewrite it later)
> Minor changes in snapshot tests

- .github/workflows/rust.yml
- .gitignore
- snapshot_tests/fit_to_resolution/green_background.scene.json
- src/snapshot_tests.rs
- src/snapshot_tests/test_case.rs
- src/snapshot_tests/tests.rs
- src/snapshot_tests/utils.rs
> Snapshot tests (part 3)

- compositor_render/src/transformations/builtin/params.rs
- src/snapshot_tests/tests.rs
Fixes: #234 
Snapshot tests: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/3
> Fix stretch to resolution

- compositor_render/src/renderer.rs
- compositor_render/src/renderer/node.rs
- compositor_render/src/renderer/render_graph.rs
- compositor_render/src/renderer/render_loop.rs
- schemas/scene.schema.json
- src/types/component.rs
- src/types/convert.rs
- src/types/from_component.rs
In new API component tree will be considered scene, so I'm renaming stuff to avoid naming issues in the follow up
> Rename parts of the old scene

- compositor_render/src/scene/components.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/view_component.rs
- compositor_render/src/scene/view_component/interpolation.rs
- compositor_render/src/scene/view_component/layout.rs
- compositor_render/src/transformations/layout.rs
- compositor_render/src/transformations/layout/flatten.rs
- compositor_render/src/transformations/layout/transformation_matrix.rs
- schemas/scene.schema.json
- snapshot_tests/image/jpeg_in_view.scene.json
- snapshot_tests/view/constant_width_views_row_with_overflow_hidden.scene.json
- snapshot_tests/view/constant_width_views_row_with_overflow_visible.scene.json
- src/snapshot_tests/tests.rs
- src/types/component.rs
- src/types/from_component.rs
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/11/files
tested only cropping views, to support it fully we need RenderLayout to support cropping
> Add `overflow=hidden` for `View` component

- compositor_render/src/scene/components.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/view_component/layout.rs
- compositor_render/src/transformations/layout.rs
- compositor_render/src/transformations/layout/flatten.rs
- schemas/scene.schema.json
- snapshot_tests/image/jpeg_in_view_overflow_fit.scene.json
- snapshot_tests/view/constant_width_views_row_with_overflow_fit.scene.json
- src/snapshot_tests/tests.rs
- src/types/component.rs
- src/types/from_component.rs
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/12
> Add `overflow=fit` option

- compositor_render/src/renderer/node.rs
- compositor_render/src/renderer/render_graph.rs
- compositor_render/src/scene.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/scene/shader_component.rs
- compositor_render/src/scene/web_view_component.rs
- compositor_render/src/transformations.rs
- compositor_render/src/transformations/web_renderer.rs
- compositor_render/src/transformations/web_renderer/chromium_sender.rs
- compositor_render/src/transformations/web_renderer/embedder.rs
- compositor_render/src/transformations/web_renderer/node.rs
- compositor_render/src/wgpu/shader/shader_params.rs
- compositor_render/src/wgpu/texture/bgra.rs
- examples/web_renderer.rs
- schemas/scene.schema.json
- src/types.rs
- src/types/component.rs
- src/types/from_component.rs
> Add `WebView` component back

- Dockerfile
- docker/entrypoint.sh
- examples/docker.rs
It will produce smaller images e.g. not target directory or other dependencies that are needed only for build
On macos do not try to connect GPU - default to software-based rendering.
> Configure multi-staged docker build

- compositor_render/src/scene.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/rescaler_component.rs
- compositor_render/src/scene/rescaler_component/interpolation.rs
- compositor_render/src/scene/rescaler_component/layout.rs
- compositor_render/src/scene/validation.rs
- compositor_render/src/scene/view_component/layout.rs
- compositor_render/src/transformations/layout.rs
- examples/image.rs
- examples/transition.rs
- schemas/scene.schema.json
- snapshot_tests/rescaler/fill_input_stream.scene.json
- snapshot_tests/rescaler/fill_input_stream_align_bottom_right.scene.json
- snapshot_tests/rescaler/fill_input_stream_align_top_left.scene.json
- snapshot_tests/rescaler/fit_input_stream.scene.json
- snapshot_tests/rescaler/fit_input_stream_align_bottom_right.scene.json
- snapshot_tests/rescaler/fit_input_stream_align_top_left.scene.json
- snapshot_tests/rescaler/fit_view_with_known_height.scene.json
- snapshot_tests/rescaler/fit_view_with_known_width.scene.json
- snapshot_tests/rescaler/fit_view_with_unknown_width_and_height.scene.json
- src/bin/update_snapshots/main.rs
- src/snapshot_tests/test_case.rs
- src/snapshot_tests/tests.rs
- src/types/component.rs
- src/types/from_component.rs
Resize, or Rescale would be better name, but we should try to use verbs for component names to keep it consistent. Initially, I started with `Scaler`, but Jerzy suggested `Rescaler`. I don't have any ideas for a better name, I'm open to suggestions.
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/18
> Add `Rescaler` component

- src/rtp_receiver.rs
Improves register time on input streams
> Skip avformat_find_stream_info

- src/bin/generate_docs/main.rs
- src/bin/generate_docs/parsing.rs
- src/bin/generate_docs/type_definition.rs
- src/types.rs
- Fixed not appearing description for some types
- Fixed optional marker not appearing after type inlining
> [docs] Fix optionals and variant descriptions in docs

- Cargo.lock
- Cargo.toml
- src/rtp_sender.rs
This still needs some cleanup work (mainly removing ffmpeg and rtp types from the rest of the compositor). I'll do that in subsequent PRs
> Remove the ffmpeg rtp sender

- compositor_chromium/chromium_sys/build.rs
- compositor_chromium/src/main_args.rs
- examples/docker.rs
- src/rtp_receiver.rs
Web renderer still does not work. I will fix it in the follow-up PR
Issue: https://github.com/membraneframework/video_compositor/issues/307
> Fix docker on MacOS

- compositor_render/src/scene.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/layout.rs
- compositor_render/src/scene/rescaler_component.rs
- compositor_render/src/scene/rescaler_component/layout.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/scene/tiles_component.rs
- compositor_render/src/scene/tiles_component/interpolation.rs
- compositor_render/src/scene/tiles_component/layout.rs
- compositor_render/src/scene/tiles_component/tiles.rs
- compositor_render/src/scene/view_component.rs
- compositor_render/src/scene/view_component/layout.rs
- compositor_render/src/transformations/layout.rs
- examples/tiles.rs
- schemas/scene.schema.json
- snapshot_tests/tiles_transitions/after_end_with_4_inputs_no_id.scene.json
- snapshot_tests/tiles_transitions/end_tile_resize.scene.json
- snapshot_tests/tiles_transitions/end_tile_resize_with_view_transition.scene.json
- snapshot_tests/tiles_transitions/end_with_3_inputs_1_id.scene.json
- snapshot_tests/tiles_transitions/end_with_3_inputs_3_id_different_order.scene.json
- snapshot_tests/tiles_transitions/end_with_4_inputs_1_id.scene.json
- snapshot_tests/tiles_transitions/end_with_4_inputs_no_id.scene.json
- snapshot_tests/tiles_transitions/end_with_5_inputs_no_id.scene.json
- snapshot_tests/tiles_transitions/start_tile_resize.scene.json
- snapshot_tests/tiles_transitions/start_with_3_inputs_all_id.scene.json
- snapshot_tests/tiles_transitions/start_with_3_inputs_no_id.scene.json
- src/snapshot_tests/tests.rs
- src/types/component.rs
- src/types/from_component.rs
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/23
https://github.com/membraneframework/video_compositor/assets/9753141/546f257e-2764-448b-bc79-536abee0cb03
> Add animations to `Tiles` component

- compositor_render/src/transformations/shader.rs
- snapshot_tests/shader/circle_layout.wgsl
- src/snapshot_tests/tests.rs
- src/types.rs
- src/types/convert.rs
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/25
> Add user shader params test

- .gitignore
- build-tools/nix/flake.lock
- build-tools/nix/flake.nix
- build-tools/nix/package.nix
- result
- src/bin/package_for_release/bundle_macos.rs
Tested on:
- NixOS
- Arch with nix
- macos intel
> Update flake.nix to handle different environments correctly

- docs/pages/api/api.md
- docs/pages/api/routes.md
- examples/common/common.rs
- schemas/register.schema.json
- src/http.rs
- src/lib.rs
- src/main.rs
- src/routes.rs
- src/types/register_request.rs
Routes:
- `POST /--/api` main endpoint used for almost everything
- `GET /status` health check - it just returns 200 response
> Add minimal router + add `/status` route

- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/queue_thread.rs
- examples/tiles.rs
- schemas/scene.schema.json
- src/api.rs
- src/api/register_request.rs
- src/api/unregister_request.rs
- src/types.rs
Adds `schedule_time_ms` field to unregister_output/unregister_input/update_scene requests
> Support scheduling request at a specific PTS

- docs/pages/api/inputs/mp4.md
- docs/pages/api/inputs/rtp.md
- docs/pages/api/routes.md
- docs/sidebars.ts
> Refactor input information and add docs about mp4s

- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/input/rtp/tcp_server.rs
- compositor_pipeline/src/pipeline/input/rtp/udp.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_pipeline/src/pipeline/rtp.rs
- docs/pages/api/routes.md
- examples/common/common.rs
- examples/rtp_tcp.rs
- schemas/register.schema.json
- src/api.rs
- src/api/register_request.rs
- src/types.rs
- src/types/from_register_request.rs
- src/types/register_request.rs
- Implement RTP over TCP on output
- Fix RTP over TCP on input. I realized that stuff like read_exact is not safe when the socket can timeout. We are reasking that some of the data is read and timeout is triggered that discards it.
> Implement RTP over TCP on output

- build_tools/nix/flake.nix
- compositor_pipeline/src/pipeline/decoder.rs
- compositor_pipeline/src/pipeline/decoder/fdk_aac.rs
- compositor_pipeline/src/pipeline/decoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/decoder/opus_decoder.rs
- compositor_pipeline/src/pipeline/input.rs
- compositor_pipeline/src/pipeline/input/mp4.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/utils.rs
- compositor_pipeline/src/queue/video_queue.rs
- examples/rtp_tcp.rs
- Handle EOS in input elements (mostly pass around, no support for RTCP goodbey yet)
- Handle EOS in queue
- if EOS received input is always marked as ready
- if EOS received and get_frame returned last frame then remove it.
Output elements and sending EOS from queue will be handled in follow up PR
> Add EOS for inputs element

- compositor_pipeline/src/audio_mixer.rs
- compositor_pipeline/src/audio_mixer/internal_audio_mixer.rs
- compositor_pipeline/src/audio_mixer/types.rs
- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/decoder.rs
- compositor_pipeline/src/pipeline/decoder/opus_decoder.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/input/rtp/depayloader.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_pipeline/src/pipeline/output/rtp/payloader.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/pipeline/rtp.rs
- examples/audio.rs
- schemas/register.schema.json
- schemas/scene.schema.json
- src/api.rs
- src/types.rs
- src/types/from_audio.rs
- src/types/from_register_request.rs
- src/types/register_request.rs
Implements audio mixer.
TODO:
Add resampler for AAC audio
Mixing - use sum and normalization instead of average
> Audio mixing

- compositor_pipeline/src/pipeline/input/mp4.rs
- compositor_pipeline/src/pipeline/input/mp4/video_reader.rs
More will come in subsequent PRs
> Extract the video reading logic from the mp4 component

- docs/pages/api/routes.md
> Update audio docs

- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- compositor_pipeline/src/pipeline/encoder/opus.rs
- compositor_pipeline/src/pipeline/input/rtp.rs
- compositor_pipeline/src/pipeline/output.rs
- compositor_pipeline/src/pipeline/output/rtp.rs
- compositor_pipeline/src/pipeline/output/rtp/packet_stream.rs
- compositor_pipeline/src/pipeline/output/rtp/payloader.rs
- compositor_pipeline/src/pipeline/output/rtp/tcp_server.rs
- compositor_pipeline/src/pipeline/output/rtp/udp.rs
- compositor_pipeline/src/pipeline/structs.rs
- Handle RTCP Goodbye on input
- Handle RTCP Goodbye on output
- Change encoder output type to specify which EOS is sent
> Support RTCP Goodbye

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/input/rtp/tcp_server.rs
- compositor_pipeline/src/pipeline/output/rtp/tcp_server.rs
- compositor_pipeline/src/pipeline/pipeline_input.rs
- compositor_pipeline/src/pipeline/pipeline_output.rs
- docs/pages/api/outputs/rtp.md
- docs/pages/api/routes.md
- docs/sidebars.ts
- schemas/register.schema.json
- src/bin/generate_docs/main.rs
- src/types.rs
- src/types/from_register_request.rs
- src/types/register_request.rs
It has not been tested yet, I'm working on a PR to a plugin to test it there.
> Add API for passing EOS to outputs

- src/api.rs
- src/api/register_request.rs
- src/routes.rs
Images and mp4 use `reqwest::blocking` underneath which does not work in async context
> Fix registering mp4 and images

- examples/audio.rs
- examples/common/common.rs
- examples/docker.rs
- examples/hls.rs
- examples/image.rs
- examples/mp4.rs
- examples/pass_through.rs
- examples/rtp_tcp.rs
- examples/simple.rs
- examples/test_pattern.rs
- examples/text.rs
- examples/tiles.rs
- examples/transition.rs
- examples/web_view.rs
This PR doesn't change what examples are doing, it just extracts common boilerplate logic and cleans up examples.
The actual content changes will be performed in subsequential PRs.
> Simplify examples

- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- compositor_render/src/transformations/layout/flatten.rs
- docs/pages/api/events.md
- docs/pages/api/routes.md
- docs/sidebars.ts
> Add docs for `/--/ws` endpoint

- compositor_integration_tests/src/bin/play_rtp_dump.rs
- compositor_integration_tests/src/common.rs
- compositor_integration_tests/src/compositor_instance.rs
- compositor_integration_tests/src/output_receiver.rs
- compositor_integration_tests/src/tests.rs
- compositor_integration_tests/src/tests/audio_mixing.rs
- compositor_integration_tests/src/tests/muxed_video_audio.rs
- compositor_integration_tests/src/tests/required_inputs.rs
- compositor_integration_tests/src/tests/schedule_update.rs
- compositor_integration_tests/src/tests/unregistering.rs
- compositor_integration_tests/src/validation.rs
- compositor_integration_tests/src/video_decoder.rs
Snapshots: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/29
> Add more integration tests

- compositor_integration_tests/src/compositor_instance.rs
- compositor_integration_tests/src/validation.rs
- examples/audio.rs
- examples/common/common.rs
- examples/docker.rs
- examples/hls.rs
- examples/image.rs
- examples/mp4.rs
- examples/pass_through.rs
- examples/rtp_tcp.rs
- examples/simple.rs
- examples/test_pattern.rs
- examples/text.rs
- examples/tiles.rs
- examples/transition.rs
- examples/web_view.rs
- src/api.rs
- src/bin/main_process.rs
- src/config.rs
- src/logger.rs
- src/main.rs
- src/routes.rs
- src/server.rs
Do not store config value globally, it is hard to customize those values in tests.
> Remove global config

- compositor_integration_tests/src/tests/audio_mixing.rs
- compositor_integration_tests/src/tests/muxed_video_audio.rs
- compositor_integration_tests/src/tests/required_inputs.rs
- compositor_integration_tests/src/tests/schedule_update.rs
- compositor_integration_tests/src/tests/unregistering.rs
Snapshot PR: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/31
> Add descriptions to integration tests and input rtp dumps

- snapshot_tests/text/root_text.scene.json
- snapshot_tests/view/empty_view.scene.json
- src/snapshot_tests/tests.rs
Add test that verify https://github.com/membraneframework/video_compositor/issues/491
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/34/
> Add tests that are verifying removing image/text from scene

- Cargo.lock
- Cargo.toml
- generate/.gitignore
- generate/Cargo.toml
- generate/src/bin/generate_docs_example_inputs.rs
- generate/src/compositor_instance.rs
- generate/src/lib.rs
Generate some input samples that can be used to show layout component examples. We can use those files as inputs and use it to generate examples of different layouts and embed it on website as WebP
https://github.com/membraneframework/video_compositor/assets/9753141/3f592d19-4fc8-40bc-8a69-21810d3f45c4
> Generate example inputs for docs

- snapshot_tests/tiles/video_call_with_labels.scene.json
- snapshot_tests/transition/change_view_absolute_cubic_bezier_end.scene.json
- snapshot_tests/transition/change_view_absolute_cubic_bezier_linear_like_end.scene.json
- snapshot_tests/transition/change_view_absolute_cubic_bezier_linear_like_start.scene.json
- snapshot_tests/transition/change_view_absolute_cubic_bezier_start.scene.json
- src/snapshot_tests/tests.rs
Snapshots PR: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/36
> Add cubic bezier snapshot tests

- integration_tests/src/bin/generate_rtp_from_file.rs
- integration_tests/src/tests.rs
- integration_tests/src/tests/aac.rs
I added a test
closes #387 
PR in snapshots:
https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/37
> Add an integration test for AAC

- compositor_pipeline/src/pipeline/pipeline_output.rs
> Ensure automatic EOS can trigger when there are no inputs

- docs/pages/concept/component.md
- docs/pages/concept/layouts.md
Hi,
By reading the docs, I think I've spotted two minors errors.
Regards,
> Docs : fix missing comma in json snippet, change "Tails" to "Tiles".

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/pipeline/pipeline_output.rs
> Simplify handling EOS

- .github/workflows/deploy_docs.yml
Required so we can add docs website in Google search console
> [docs] add google site verification

- compositor_pipeline/src/pipeline.rs
- compositor_pipeline/src/queue.rs
- compositor_pipeline/src/queue/audio_queue.rs
- compositor_pipeline/src/queue/video_queue.rs
- docs/pages/deployment/configuration.md
- src/config.rs
- src/types/from_register_input.rs
> Option to configure input latency

- docs/src/pages/index.module.css
- docs/src/pages/index.tsx
https://github.com/membraneframework/live_compositor/pull/633 was suppose to change only the text of secondary title, but a lot of other text was also updated as a result.
> [website] Revert font size changes

- compositor_api/src/types.rs
- compositor_api/src/types/component.rs
- compositor_api/src/types/from_register_input.rs
- compositor_api/src/types/from_register_output.rs
- compositor_api/src/types/register_input.rs
- compositor_api/src/types/register_output.rs
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/encoder/fdk_aac.rs
- compositor_pipeline/src/pipeline/encoder/opus.rs
- compositor_pipeline/src/pipeline/output.rs
- compositor_pipeline/src/pipeline/output/mp4.rs
- compositor_pipeline/src/pipeline/types.rs
- compositor_render/src/types.rs
- docs/pages/api/inputs/mp4.md
- docs/pages/api/outputs/mp4.md
- docs/pages/api/outputs/rtp.md
- docs/pages/api/routes.md
- docs/pages/guides/receive-output.md
- docs/sidebars.ts
- generate/src/bin/generate_from_types/generate_docs.rs
- integration_tests/examples/encoded_channel_output.rs
- integration_tests/examples/mp4.rs
- integration_tests/src/tests/push_input_before_start.rs
- src/routes/register_request.rs
Adds AAC encoder and fixes MP4 audio output
> Add AAC encoder, fixed MP4 output

- build_tools/nix/flake.nix
I missed that in https://github.com/software-mansion/live-compositor/pull/668
> Add missing nix `mesa.drivers` package

- ts/@live-compositor/core/package.json
- ts/@live-compositor/core/src/compositor.ts
- ts/@live-compositor/core/src/output.ts
- ts/@live-compositor/core/src/renderer.ts
- ts/@live-compositor/node/package.json
- ts/examples/.gitignore
- ts/examples/README.md
- ts/examples/package.json
- ts/examples/src/dynamic-inputs.tsx
- ts/examples/src/news-ticker.tsx
- ts/examples/src/utils.ts
- ts/lerna.json
- ts/live-compositor/package.json
- ts/live-compositor/src/hooks/store.ts
- ts/live-compositor/src/hooks/useInputStream.ts
- ts/live-compositor/src/index.ts
- ts/package-lock.json
- ts/package.json
- Add `useInputStreams` to interact with new streams
- Add lerna + improve build/release automation (e.g. running npm run watch for all workspaces)
- Ensure package is build when publishing
> [ts-sdk] Add `useInputStreams` hook

- .github/workflows/wasm.yml
Issue: https://github.com/software-mansion/live-compositor/issues/653
> WASM checks in CI

- compositor_web/src/wasm.rs
- compositor_web/src/wasm/input_uploader.rs
- compositor_web/src/wasm/output_downloader.rs
- compositor_web/src/wasm/types.rs
Issue: https://github.com/software-mansion/live-compositor/issues/653
> Unregister API for `compositor_web`

- Cargo.lock
- Cargo.toml
- compositor_render/Cargo.toml
- compositor_render/src/state.rs
- compositor_render/src/transformations/text_renderer.rs
- compositor_web/Cargo.toml
- compositor_web/src/wasm.rs
Font has to be prefetched before it can be used. I was not able to load browser's fonts so every font has to be provided by the user.
Issue: https://github.com/software-mansion/live-compositor/issues/653
> Make text component work on wasm

- compositor_api/src/types/register_input.rs
> [docs] Add MP4 loop version docs info

- docs/src/components/PlaygroundSettings.module.css
- docs/src/components/PlaygroundSettings.tsx
- docs/src/components/PlaygroundSettingsImages.module.css
- docs/src/components/PlaygroundSettingsImages.tsx
- docs/src/components/PlaygroundSettingsInputs.tsx
- docs/src/components/PlaygroundSettingsShaders.module.css
- docs/src/components/PlaygroundSettingsShaders.tsx
- added shaders descriptions modal
- corrected person image resolution description
> [playground] Add shaders descriptions modal

- docs/src/components/PlaygroundSettingsShaders.tsx
FIxed shaders modal tooltip code to include quotes
> [playground] Fix shader tooltip code

- docs/src/pages/playground.tsx
400px is a bit to much, on macbook in full screen this is already causing that div above to be different size
> [playground] Change playground setting min height

- ts/@live-compositor/node/src/fetch.ts
- ts/live-compositor/src/components/Tiles.ts
https://github.com/node-fetch/node-fetch/issues/1735
> [ts-sdk] Fix for Node.js 20

- demos/2-tv_broadcast/index.ts
> [demos] Fix missing asset

- integration_tests/examples/docker.rs
- integration_tests/src/examples.rs
regression from examples refactor
> [tests] Fix integration_tests docker example

- docs/pages/deployment/requirements.md
I added required stuff needed on new mac to build from source.
Both pkg-config and cmake were required by chromium to work
> [docs] Update building from source requirements

- README.md
- Removing copyright section, there is no point to keep it
- Adding section about SWM (this is consistent across all multimedia projects in SWM)
> Add made by section to README

- vk-video/src/parser/reference_manager.rs
This implements sections 8.2.4.3.1 from the spec.
Closes #804
> [vk-video] Process modification of short-term reference picture list

- vk-video/src/parser/au_splitter.rs
- vk-video/src/vulkan_decoder/vulkan_ctx.rs
Reformat some files, romove unclear/wrong TODOs, lower severity of annoying and not useful logs.
> [vk-video] Various minor fixes

- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/session_resources.rs
Before this change we relied on `max_coded_extent` being the video size, wich is not always the case, especially not in mp4 files. This PR fixes that and we extract the correct dimensions from the sps.
This reuired storing sps and pps in the decoder in addition to them being stored on the GPU.
Closes #826
> [vk-video] Get picture dimensions for download/transfer correctly

- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
Fixes https://github.com/software-mansion/live-compositor/issues/781
> Flush encoder on EOS

- vk-video/build.rs
- vk-video/src/parser.rs
- vk-video/src/parser/reference_manager.rs
This PR implements mainly section 8.2.5.4 from the spec.
Closes #805.
> [vk-video] Add support for long-time references

- compositor_render/src/transformations/text_renderer.rs
> Fix scene update failing if `text` in `Text` component is empty

- .github/workflows/deploy_docs.yml
Docs will be fully reworked, so we don't want to show partial state in the meantime,
> [docs] Disable auto-deploy

- Cargo.lock
- compositor_pipeline/src/pipeline/decoder/video/vulkan_video.rs
- integration_tests/examples/vulkan.rs
- vk-video/Cargo.toml
- vk-video/examples/basic.rs
- vk-video/examples/wgpu.rs
- vk-video/src/lib.rs
- vk-video/src/parser.rs
- vk-video/src/parser/au_splitter.rs
- vk-video/src/parser/nalu_parser.rs
- vk-video/src/parser/nalu_splitter.rs
- vk-video/src/parser/reference_manager.rs
- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/frame_sorter.rs
- vk-video/src/vulkan_decoder/session_resources.rs
- vk-video/src/vulkan_decoder/session_resources/images.rs
- vk-video/src/vulkan_decoder/vulkan_ctx.rs
- vk-video/src/vulkan_decoder/wrappers/mem.rs
- vk-video/src/vulkan_decoder/wrappers/parameter_sets.rs
- vk-video/src/vulkan_decoder/wrappers/video.rs
This was simpler than I expected, and did not require as many changes in the code as I anticipated.
Closes #831
> Add support for b-frame decoding

- Cargo.lock
- vk-video/Cargo.toml
https://github.com/membraneframework-labs/h264-reader/commit/9292ad0ab24b75e07815f546f41cef24b30b09c9
> Remove LFS file from h264-reader fork

- Cargo.lock
- Cargo.toml
- compositor_render/Cargo.toml
- compositor_render/src/wgpu/common_pipeline.rs
- compositor_render/src/wgpu/format/interleaved_yuv_to_rgba.rs
- compositor_render/src/wgpu/format/nv12_to_rgba.rs
- compositor_render/src/wgpu/format/planar_yuv_to_rgba.rs
- compositor_render/src/wgpu/format/rgba_to_yuv.rs
- compositor_render/src/wgpu/utils/r8_fill_with_color.rs
- compositor_web/Cargo.toml
- vk-video/Cargo.toml
- vk-video/examples/player/player/renderer.rs
- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/vulkan_ctx.rs
This reverts commit 505fc0743899cf28bde20a72961ad4cee7056eaf.
Related #874
> Revert "Update wgpu to 23.0.0 (#846)"

- .github/workflows/package_for_release.yml
- build_tools/docker/full.Dockerfile
- build_tools/docker/slim.Dockerfile
- scripts/release.sh
- src/bin/package_for_release/bundle_linux.rs
- src/bin/package_for_release/bundle_macos.rs
> Publish docker image as part of the release process

- ts/@live-compositor/web-wasm/src/compositor/compositor.ts
- ts/@live-compositor/web-wasm/src/mainContext/instance.ts
- ts/@live-compositor/web-wasm/src/mainContext/output/whip.ts
- ts/@live-compositor/web-wasm/src/workerContext/pipeline.ts
- ts/@live-compositor/web-wasm/src/workerContext/queue.ts
- ts/examples/vite-browser-render/src/examples/WhipExample.tsx
setInterval can drift, this implementation avoids that plus handles a case where rendering is too slow to maintain framerate
> [web-wasm] Improve queue tick

- ts/smelter-node/src/live/compositor.ts
- ts/smelter-node/src/offline/compositor.ts
Add missing methods that were accidentally removed in https://github.com/software-mansion/smelter/commit/497b0bc10444afb44440cc9ee54414cae9d8e59c
> [ts-sdk] Add missing register methods

- compositor_api/src/types/component.rs
- schemas/scene.schema.json
- ts/smelter/src/api.generated.ts
Delete unused field from Tiles component
> Delete `border_radius` field from Tiles component

- .github/workflows/package_for_release.yml
This is the only approach that I found working
> Display docker arm64 image on the top

- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline/encoder.rs
- compositor_pipeline/src/pipeline/encoder/fdk_aac.rs
- compositor_pipeline/src/pipeline/output.rs
- compositor_pipeline/src/pipeline/output/mp4.rs
- ts/examples/node-examples/src/combine_mp4.tsx
Mp4 that was generated before does not work in quicktime
> Fix muxing AAC in MP4 (missing metadata)

- ts/examples/vite-example/src/examples/ComponentMp4Example.tsx
- ts/smelter-web-wasm/src/mainContext/AudioMixer.ts
- ts/smelter-web-wasm/src/workerContext/input/source/Mp4Demuxer.ts
- ts/smelter-web-wasm/src/workerContext/input/source/Mp4Source.ts
Mp4 without audio track was blocked while waiting for first audio chunk on init
> [ts-sdk] Fix mp4 without audio

- compositor_render/src/scene/rescaler_component/layout.rs
- compositor_render/src/scene/types.rs
- compositor_render/src/scene/view_component/layout.rs
- snapshot_tests/view/border_radius_clipping.scene.json
- snapshot_tests/view/border_radius_clipping_large_border_width.scene.json
- src/snapshot_tests/view_tests.rs
Snapshots PR: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/54
Closes: #1017
> Clip border radius

- ts/smelter-web-wasm/src/compositor/api.ts
missing resolution when registering svg
> [ts-sdk] Fix WASM registerImage types

- compositor_pipeline/src/pipeline/encoder/ffmpeg_h264.rs
- integration_tests/src/bin/benchmark/args.rs
- integration_tests/src/bin/benchmark/benchmark.rs
- integration_tests/src/bin/benchmark/benchmark_pass.rs
- integration_tests/src/bin/benchmark/main.rs
- integration_tests/src/bin/benchmark/maximize_iter.rs
- integration_tests/src/bin/benchmark/scenes.rs
- integration_tests/src/bin/benchmark/suite.rs
- integration_tests/src/bin/benchmark/utils.rs
Prepare the codebase so we can define benchmark suites in code. Actual definitions will land in a separate PR
Regression:
- It's not possible to iterate over args, just maxmize or specific value
- Remove CSV export in favor or JSON
> Refactor benchmark code

- CHANGELOG.md
- compositor_chromium/src/v8/array_buffer.rs
- compositor_render/src/transformations/web_renderer/process_helper/handler.rs
- compositor_render/src/transformations/web_renderer/process_helper/state.rs
It's a temporary fix #1031 
The fix introduces additional frame data copy on embedding frames.
> Fix for not working `chromium_embedding`

- snapshot_tests/transition/change_view_width_transition_interrupt_end_variant1.scene.json
- snapshot_tests/transition/change_view_width_transition_interrupt_end_variant2.scene.json
- snapshot_tests/transition/change_view_width_transition_interrupt_start.scene.json
- src/snapshot_tests/transition_tests.rs
Snapshot PR: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/57
> [tests] Test transition interrupt

- compositor_render/src/scene.rs
- compositor_render/src/scene/components.rs
- compositor_render/src/scene/image_component.rs
- compositor_render/src/scene/scene_state.rs
- compositor_render/src/state/node.rs
- compositor_render/src/transformations/image.rs
- compositor_render/src/transformations/image/animated_image.rs
- snapshot_tests/image/gif_as_root_variant1.scene.json
- snapshot_tests/image/gif_as_root_variant2.scene.json
- src/snapshot_tests/image_tests.rs
Snapshot PR: https://github.com/membraneframework-labs/video_compositor_snapshot_tests/pull/59
> Keep gif animation state between scene updates

- integration_tests/src/tests/required_inputs.rs
> [tests] Update audio allowed error

- ts/smelter-core/src/index.ts
- ts/smelter-core/src/utils.ts
- ts/smelter-node/src/live/compositor.ts
- ts/smelter-node/src/offline/compositor.ts
- ts/smelter-web-client/src/smelter/live.ts
- ts/smelter-web-client/src/smelter/offline.ts
- ts/smelter-web-wasm/src/compositor/compositor.ts
Closes https://github.com/software-mansion/smelter/issues/1133
> [ts-sdk] Synchronize calls to smelter

- compositor_pipeline/src/audio_mixer/prepare_inputs.rs
- compositor_pipeline/src/audio_mixer/prepare_inputs/single_frame_tests.rs
> Fixed panic in `prepare_input_samples`.

- compositor_api/src/input/hls.rs
- compositor_api/src/input/hls_into.rs
- compositor_api/src/input/mp4.rs
- compositor_api/src/input/mp4_into.rs
- compositor_pipeline/src/codecs.rs
- compositor_pipeline/src/error.rs
- compositor_pipeline/src/pipeline/hls/hls_input.rs
- compositor_pipeline/src/pipeline/mp4/mp4_input.rs
- compositor_pipeline/src/protocols/hls.rs
- compositor_pipeline/src/protocols/mp4.rs
- integration_tests/examples/encoded_channel_output.rs
- integration_tests/examples/hls_input.rs
- integration_tests/examples/raw_channel_output.rs
- integration_tests/src/bin/benchmark/benchmark_pass.rs
- ts/smelter-core/src/api/input.ts
- ts/smelter-core/src/offline/output.ts
- ts/smelter/src/api.generated.ts
- ts/smelter/src/types/input.ts
- ts/smelter/src/types/input/common.ts
- ts/smelter/src/types/input/hls.ts
- ts/smelter/src/types/input/mp4.ts
- ts/smelter/src/types/input/rtp.ts
- ts/smelter/src/types/input/whip.ts
> Support specifying decoders for codecs in mp4 and hls

- vk-video/src/parser.rs
- vk-video/src/parser/au_splitter.rs
Previously, SPS and PPS NALUs were immediately converted into
`DecoderInstructions` in the parser, while slices (both P and I) were
pushed into `AuSplitter`. This meant a reorder was possible:
1. P frame pushed into `AuSplitter`
2. SPS and PPS returned as decoder instructions
3. I frame pushed into `AuSplitter`, which detects that the I frame
belongs to a different access unit and returns the P frame
In this case, the order was turned from P, SPS, PPS, I into SPS, PPS, P,
I, which is problematic, because the P-frame could be referring to
previous SPS, which are overridden before the P frame can be decoded.
This patch pushes SPS and PPS through the `AuSplitter` to avoid such
cases.
> Fix P-frame reorder

- vk-video/src/vulkan_encoder.rs
- vk-video/src/vulkan_encoder/encode_parameter_sets.rs
> [vk-video] Support resolutions divisible by 16 in encoder

- vk-video/src/parser.rs
- vk-video/src/parser/au_splitter.rs
- vk-video/src/vulkan_decoder.rs
- vk-video/src/vulkan_decoder/session_resources.rs
- vk-video/src/vulkan_decoder/session_resources/parameters.rs
- vk-video/src/wrappers/parameter_sets.rs
> [vk-video] Handle decoder restarts

- compositor_pipeline/src/pipeline/webrtc/server.rs
- compositor_pipeline/src/pipeline/webrtc/server/create_whep_session.rs
- compositor_pipeline/src/pipeline/webrtc/server/new_whep_ice_candidates.rs
- compositor_pipeline/src/pipeline/webrtc/server/terminate_whep_session.rs
Rename WHEP routes `:id->:endpoint_id`
> Rename WHEP routes

- compositor_api/src/output/rtmp.rs
- compositor_api/src/output/rtmp_into.rs
- integration_tests/examples/whep_server.rs
- integration_tests/examples/whip_client.rs
- integration_tests/examples/whip_server.rs
- src/routes/register_request.rs
- ts/examples/vite-example/src/components/SmelterWhipOutput.tsx
- ts/examples/vite-example/src/smelter-examples/WhepClientExample.tsx
- ts/smelter-core/src/api/input.ts
- ts/smelter-core/src/api/output.ts
- ts/smelter-core/src/api/output/whep.ts
- ts/smelter-core/src/api/output/whip.ts
- ts/smelter-core/src/live/compositor.ts
- ts/smelter-core/src/offline/compositor.ts
- ts/smelter-node/src/api.ts
- ts/smelter-node/src/live/compositor.ts
- ts/smelter-node/src/offline/compositor.ts
- ts/smelter-web-client/src/api.ts
- ts/smelter-web-client/src/smelter/live.ts
- ts/smelter-web-client/src/smelter/offline.ts
- ts/smelter-web-wasm/README.md
- ts/smelter-web-wasm/src/compositor/api.ts
- ts/smelter-web-wasm/src/mainContext/input.ts
- ts/smelter-web-wasm/src/workerApi.ts
- ts/smelter/src/api.generated.ts
> Rename WHIP/WHEP inputs/outputs

- compositor_pipeline/src/audio_mixer/prepare_inputs.rs
- compositor_pipeline/src/audio_mixer/prepare_inputs/consecutive_frames_tests.rs
- compositor_pipeline/src/audio_mixer/prepare_inputs/single_frame_tests.rs
> Fixed clicking in audio with offset set.

- compositor_pipeline/src/pipeline/hls/hls_input.rs
Remove log statement accidentally left in the code
> Remove old debug log

- compositor_api/src/input/whip.rs
- compositor_api/src/input/whip_into.rs
- compositor_pipeline/src/codecs.rs
- compositor_pipeline/src/graphics_context.rs
- compositor_pipeline/src/pipeline/webrtc/whip_input.rs
- compositor_pipeline/src/protocols/webrtc.rs
- ts/smelter/src/api.generated.ts
> Resolve WHIP decoder preferences based on `vulkan` support

- integration_tests/examples/demo/inputs/rtp.rs
- integration_tests/examples/demo/main.rs
- integration_tests/examples/demo/outputs/rtp.rs
- integration_tests/examples/demo/smelter_state.rs
> [examples] Added option to reorder inputs in interactive example.

- integration_tests/examples/demo/inputs.rs
- integration_tests/examples/demo/inputs/rtp.rs
- integration_tests/examples/demo/main.rs
- integration_tests/examples/demo/outputs.rs
- integration_tests/examples/demo/outputs/rtp.rs
- integration_tests/examples/demo/outputs/whep.rs
- integration_tests/examples/demo/smelter_state.rs
- integration_tests/examples/demo/whep.html
Closes #1256 
Adds `WHEP` output to interactive example.
Additionally adjusts code to  #1303.
> [examples] Added `WHEP` output

- Cargo.lock
- integration_tests/Cargo.toml
- integration_tests/examples/demo/autocompletion.rs
- integration_tests/examples/demo/inputs/mp4.rs
- integration_tests/examples/demo/inputs/rtp.rs
- integration_tests/examples/demo/main.rs
- integration_tests/examples/demo/outputs/mp4.rs
- integration_tests/examples/demo/outputs/rtmp.rs
- integration_tests/examples/demo/outputs/rtp.rs
- integration_tests/examples/demo/outputs/scene.rs
- integration_tests/examples/demo/outputs/whep.rs
- integration_tests/examples/demo/outputs/whip.rs
> [examples] Added `Reset` option

- integration_tests/examples/demo/autocompletion.rs
- integration_tests/examples/demo/inputs/mp4.rs
> [examples] Added `URL` input source to `MP4` input in interactive example.

- integration_tests/examples/demo/inputs.rs
- integration_tests/examples/demo/inputs/hls.rs
- integration_tests/examples/demo/inputs/mp4.rs
- integration_tests/examples/demo/inputs/rtp.rs
- integration_tests/examples/demo/inputs/whip.rs
- integration_tests/examples/demo/main.rs
- integration_tests/examples/demo/outputs.rs
- integration_tests/examples/demo/outputs/hls.rs
- integration_tests/examples/demo/outputs/mp4.rs
- integration_tests/examples/demo/outputs/rtmp.rs
- integration_tests/examples/demo/outputs/rtp.rs
- integration_tests/examples/demo/outputs/scene.rs
- integration_tests/examples/demo/outputs/whep.rs
- integration_tests/examples/demo/outputs/whip.rs
- integration_tests/examples/demo/players.rs
- integration_tests/examples/demo/smelter_state.rs
> [examples] Added `HLS` output

- integration_tests/examples/demo/INSTRUCTION.md
- integration_tests/examples/demo/inputs.rs
- integration_tests/examples/demo/inputs/hls.rs
- integration_tests/examples/demo/inputs/mp4.rs
- integration_tests/examples/demo/inputs/rtp.rs
- integration_tests/examples/demo/inputs/whip.rs
- integration_tests/examples/demo/main.rs
- integration_tests/examples/demo/outputs.rs
- integration_tests/examples/demo/outputs/hls.rs
- integration_tests/examples/demo/outputs/mp4.rs
- integration_tests/examples/demo/outputs/rtmp.rs
- integration_tests/examples/demo/outputs/rtp.rs
- integration_tests/examples/demo/outputs/scene.rs
- integration_tests/examples/demo/outputs/whep.rs
- integration_tests/examples/demo/outputs/whip.rs
- integration_tests/examples/demo/players.rs
- integration_tests/examples/demo/smelter_state.rs
> [examples] Created instruction for interactive example.

- integration-tests/examples/demo/inputs/whip.rs
- integration-tests/examples/demo/whip.html
> [examples] Added `WHIP` html sample input.

- integration-tests/examples/demo/inputs.rs
- integration-tests/examples/demo/inputs/hls.rs
- integration-tests/examples/demo/inputs/mp4.rs
- integration-tests/examples/demo/inputs/rtp.rs
> [examples] Added Vulkan decoder to inputs.
